### ISSUE TITLE
NM-Puzzle: Error al correr test de manhattan distance. Heurística inicializada incorrectamente.

### ISSUE THREAD

**Issue by domingo2000** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#10]
Hola, estaba tratando de implementar la primera parte de la tarea y me arroja el siguiente error en el test (que es con el código que ya venía en la tarea)
![image](https://user-images.githubusercontent.com/40220174/133108080-8ff9d841-c6ed-4a06-971d-42f3f76a1f2c.png)
Estoy corriendo algo mal?

**Comment by domingo2000** [comment]
Nueva info, averiguando un poco me di cuenta que en el test al hacer la lista por comprensión de las heurísticas se estaba llamando al __init__ en vez de __call__, por lo que se instanciaban las heuristicas pasando los states como argumento, cambie un par de lineas y lo deje así y ahora me funciona, para que revisen los test que pasaron en el enunciado.
![image](https://user-images.githubusercontent.com/40220174/133117557-f4392808-8575-4012-86a5-287a8e0e3f35.png)

**Comment by Dietr1ch** [comment]
Hmm, es demasiado fácil romper tests deshabilitados :/

Hay un typo en tu propuesta, pero es la correcta

```python
        heuristics = [hc(problem) for hc in problem.all_heuristics()]
        h_values = [h(start) for h in heuristics]
        assert h_values == [1, 0]
```

Voy a actualizar el repo base, pero como las tareas parten con una copia no van a ser actualizadas de forma automática.

git soporta patches, así que una opción es depender de que usen `git apply`, pero como son cambios chicos puede que
replicarlos a mano les salga mucho más fácil.

**Comment by jiaranda** [comment]
Creo que deberían avisar sobre este cambio, no todos están acostumbrados a revisar las issues.

**Comment by FeBalla** [comment]
> Creo que deberían avisar sobre este cambio, no todos están acostumbrados a revisar las issues.

Gracias por avisar, el profesor lo acaba de comentar a través de un anuncio por Canvas
