### ISSUE TITLE
[Tarea 2] Modelos repetidos con respuestas iguales

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#100]
Hola, al correr mi modelo de la pregunta de statues, me da un total de 8 modelos con respuestas iguales (o al menos iguales en los exec y holds), por lo que asumo que son varios modelos por algunas variaciones en otras variables distintas a las que nos interesan. Está bien que pase esto? O el modelo resultante debería ser único?

**Comment by Dietr1ch** [comment]
> Hola, al correr mi modelo de la pregunta de statues, me da un total de 8 modelos con respuestas iguales (o al menos iguales en los exec y holds), por lo que asumo que son varios modelos por algunas variaciones en otras variables distintas a las que nos interesan.

Claro, si quitas `#show holds/2.` y `#show exec/2.` de [strips.lp](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Planning-ASP/blob/master/planning/strips.lp#L60-L61) vas a poder ver qué los hace distintos y simplificar o restringir tu modelo si es posible.

> Está bien que pase esto? O el modelo resultante debería ser único?

Está bien, de todas maneras varias instancias de problemas podrían tener soluciones múltiples.
