### ISSUE TITLE
[Tarea 2] Blocks - Hay un limite en cuanto a cuantos bloques se pueden poner en la tabla?

### ISSUE THREAD

**Issue by Zetaku1** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#101]
Hola! en el ejemplo 0.lp

```
%                   |---|   |
%                   | a |   |  
%        |---|      |---|   | 
%        | c |      | b |   |  
%  |---| |---|  =>  |---|   |  
%  | b | | a |      | c |   |
% ------------------------
```

Si es si es que hubiera mas bloques encima de c, podría ponerlos a todos en la tabla o hay un limite?

**Comment by Dietr1ch** [comment]
Solo se puede mover el bloque que está al tope de cada stack.

La idea es dar comandos seguros a ambos brazos sin arriesgar que se caiga la torre o choquen los brazos
