### ISSUE TITLE
[Tarea 2] Café - Instanciación problema

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#104]
Hola, podemos asumir que la instancia del problema, contendrá todo el dominio y el building layout (connected), correctamente instanciado y consistente. Es decir, que si tengo `office(o23).`, entonces también tendréa `room(023).`?

**Comment by Zetaku1** [comment]
> No, puede que sólo esté `office(o23).`.

Colgándome de esta duda, si o si debe existir algo como kitchen(kitchen1) o no? Si no fuera el caso no tendríamos manera de saber si hay una room que sea kitchen.

**Comment by Dietr1ch** [comment]
> > No, puede que sólo esté `office(o23).`.
> 
> Colgándome de esta duda, si o si debe existir algo como kitchen(kitchen1) o no? Si no fuera el caso no tendríamos manera de saber si hay una room que sea kitchen.

Si. Al principio del ejemplo están mencionados todos los predicados de dominios, incluyendo `kitchen/1`.
