### ISSUE TITLE
[Tarea 2] Strips - Acciones permitidas

### ISSUE THREAD

**Issue by franciscogazitua** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#105]
Hola, en las distintas partes de la tarea donde utilizamos strips aparecen acciones sugeridas, como por ejemplo la acción move, sin embargo no me queda muy claro cuanta libertad tenemos al momento de crear acciones. Mi duda viene en si se pueden crear más acciones de las sugeridas, por ejemplo, no me queda claro si el objetivo de Statues es que podamos restringir el uso de la acción move sin recurrir a otras acciones o si está bien crear, por ejemplo,  una acción stay que se ejecute cuando no se pueda ejecutar move.

**Comment by Dietr1ch** [comment]
> Hola, en las distintas partes de la tarea donde utilizamos strips aparecen acciones sugeridas, como por ejemplo la acción move, sin embargo no me queda muy claro cuanta libertad tenemos al momento de crear acciones.

Pueden crear acciones con más parámetros, o incluso especializarlas y particianarlas mientras entregues una manera de construir la acción simple esperada (Ver #98).

> Mi duda viene en si se pueden crear más acciones de las sugeridas, por ejemplo, no me queda claro si el objetivo de Statues es que podamos restringir el uso de la acción move sin recurrir a otras acciones o si está bien crear, por ejemplo, una acción stay que se ejecute cuando no se pueda ejecutar move.

En Statues falta una acción que no haga nada, ya que [`strips.lp:21`](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Planning-ASP/tree/master/planning/strips.lp#L21) escoge una acción cada turno. Puedes simplemente crear una como `action(wait).` o `action(stay)` como sugeriste.
