### ISSUE TITLE
[Tarea 2] Restricciones problema café

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#109]
Hola, si un robot está en una cocina, puede prepar todos los tragos y después empezar a repartirlos? O hay alguna restriccion sobre esto?

**Comment by VicenteMerino** [comment]
Asimismo quiero saber si puedo tomar un trago (está con has el fluente) y después empezar a preparar otro (sin soltar el primero). Supongo que no, ya que si el robot tiene dos manos, no puedo estar haciendo ambas a la vez. Por su parte puedo tener el café (está con has) y abrir una puerta? Asumiendo que los robots tienen  dos manos me parece un supuesto válido.

**Comment by FeBalla** [comment]
Hola, podrías separar las dudas en _issues_ diferentes, por favor? para mantener la consistencia

**Comment by VicenteMerino** [comment]
@FeBalla listo, las puse en #113 #114 y #115
