### ISSUE TITLE
[Tarea 1] Admisibilidad y consistencia

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#11]
Hola, para este tipo de preguntas, hay que demostrar la admisibilidad y consistencias de las heurísticas. O basta con explicarlo?

**Comment by FeBalla** [comment]
> Hola, para este tipo de preguntas, hay que demostrar la admisibilidad y consistencias de las heurísticas. O basta con explicarlo?

No hay necesidad de que la demostración sea estrictamente matemática, ya que no es lo que se busca evaluar. Sin embargo, deben preocuparse de que su explicación sea **lo suficientemente rigurosa como para que quede muy claro** su punto y que entienden lo que están haciendo.
