### ISSUE TITLE
[Tarea 2]: Coffee - Programa insatisfacible al usar room en vez de kitchen

### ISSUE THREAD

**Issue by crvargasu** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#112]
Hola, no habia tenido ningún problema con clingo, pero ahora me topé con un error muy extraño. Llevo bastante rato intentando encontrar el motivo sin lograrlo.

Resulta que tuve un error, el cual lo reducí a esto.
```
#show could_move/3.
room(Kitchen) :- kitchen(Kitchen).
holds(0, agentAt(kitchen1)).
action_ppre(open(Door), agentAt(SrcRoom)) :- could_move(SrcRoom, DstRoom, Door),room(SrcRoom).
```
Donde me doy cuenta que ese trozo de codigo no funciona, sin embargo, el siguiente código si lo hace:
```
#show could_move/3.
room(Kitchen) :- kitchen(Kitchen).
holds(0, agentAt(kitchen1)).
action_ppre(open(Door), agentAt(SrcRoom)) :- could_move(SrcRoom, DstRoom, Door),kitchen(SrcRoom).
```
Es decir, solo cuando le especifico que el SrcRoom es kitchen me responde, de lo contrario, el código es insatisfacible. A pesar de que tengo la sentencia `room(Kitchen) :- kitchen(Kitchen).`, para que todas las kitchen sean room también. Qué estoy haciendo mal?

**Comment by FeBalla** [comment]
No estoy muy seguro si estoy entendiendo tu problema, copié literalmente tu instancia y solamente estas líneas de código:
```
#show could_move/3.
room(Kitchen) :- kitchen(Kitchen).
holds(0, agentAt(kitchen1)).
action_ppre(open(Door), agentAt(SrcRoom)) :- could_move(SrcRoom, DstRoom, Door),room(SrcRoom).
```
y el programa sí es satisfacible, por lo que **las reglas que están generando el problema deberían ser otras**. Lo que recomendaría es partir con esas reglas e ir agregando poco a poco las demás, para que determines en qué punto se te vuelve el modelo insatisfacible. De todos modos, me sería de gran utilidad si me pudieras aclarar si no estoy entendiendo bien tu duda.

**Comment by crvargasu** [comment]
Me podrías mandar exactamente el trozo que te dio satisfacible? Para evitar confusiones

**Comment by crvargasu** [comment]
Pero también está `action_ppre(open(dk),agentAt(kitchen1))`, el cual si se debería cumplir, dado que se tiene `holds(0, agentAt(kitchen1))` y `could_move(kitchen1,hallway2,dk)`.
