### ISSUE TITLE
[Tarea 2] Café - Restricción sobre tener café (has)

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#114]
Hola, quiero saber si puedo tomar un trago (está con has el fluente) y después empezar a preparar otro (sin soltar el primero). Supongo que no, ya que si el robot tiene dos manos, no puedo estar haciendo ambas a la vez. Por su parte puedo tener el café (está con has) y luego abrir una puerta? Asumiendo que los robots tienen dos manos me parece un supuesto válido.

**Comment by fbarrosalcalde** [comment]
Si me refiero a lo mismo, si el robot puede llevar más de un drink a la vez cuando se mueve.

**Comment by Dietr1ch** [comment]
> Hola, quiero saber si puedo tomar un trago (está con has el fluente) y después empezar a preparar otro (sin soltar el primero).

Luego de preparar un trago, queda en la pieza, no en el robot.
`has(Robot, Drink)` permite que cada robot tenga un trago de cada uno.


> Supongo que no, ya que si el robot tiene dos manos, no puedo estar haciendo ambas a la vez.

En ninguna parte se dice esto.

> Por su parte puedo tener el café (está con has) y luego abrir una puerta? Asumiendo que los robots tienen dos manos me parece un supuesto válido.

Si, se puede tener un trago de cada uno, y abrir puertas sin problemas. Piensa que el robot tiene una bandeja con espacio para dejar cada tipo de taza

**Comment by VicenteMerino** [comment]
Me quedo la duda sobre la segunda respuesta, si en T has(Drink) es verdadero, es posible que en T+1 se ejecute prepare(Drink2)?

**Comment by Dietr1ch** [comment]
> Me quedo la duda sobre la segunda respuesta, si en T has(Drink) es verdadero, es posible que en T+1 se ejecute prepare(Drink2)? O no sé si entendí bien que es lo que quiere decir has

Si en `holds(t0, has(Drink))` en `t0` mismo se puede hacer `prepare(Drink2)` si es que `Drink2` es un trago distinto.

**Comment by Coolgatty** [comment]
> > Me quedo la duda sobre la segunda respuesta, si en T has(Drink) es verdadero, es posible que en T+1 se ejecute prepare(Drink2)? O no sé si entendí bien que es lo que quiere decir has
> 
> Si en `holds(t0, has(Drink))` en `t0` mismo se puede hacer `prepare(Drink2)` si es que `Drink2` es un trago distinto.

hola me confunde un poco esto; si un robot `has(Drink)` y luego puede preparar otro trago, no entiendo el por que debe ser distinto si el trago quedara en la cocina de todas formas. Creo que la limitacion deberia ser que el robot no pueda hacer `take(Drink)` si `has(Drink)` pero `prepare(Drink)` deberia ser libre mientras not `has(Kitchen, Drink)`.

**Comment by Dietr1ch** [comment]
Oh, perdón, me equivoqué.
Un agente no puede preparar un trago si la cocina en donde está ya tiene
ese trago. Que el agente tenga o no ese trago no influye, ya que el agente
no recibe directamente el trago nuevo.

Antonio ***@***.***> schrieb am So., 17. Okt. 2021, 01:16:

**Comment by Coolgatty** [comment]
Entiendo pero para dejarlo super claro es como digo yo cierto? :D

**Comment by Coolgatty** [comment]
> Oh, perdón, me equivoqué.
Un agente no puede preparar un trago si la cocina en donde está ya tiene
ese trago. Que el agente tenga o no ese trago no influye, ya que el agente
no recibe directamente el trago nuevo.

Entiendo pero para dejarlo super claro es como digo yo cierto? Asi:

> Creo que la limitacion deberia ser que el robot no pueda hacer `take(Drink)` si `has(Drink)` pero `prepare(Drink)` deberia ser libre mientras `not has(Kitchen, Drink)`.
