### ISSUE TITLE
NM-Puzzle: Valores de Heuristica Manhattan Distance de un test no son admisibles.

### ISSUE THREAD

**Issue by domingo2000** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#12]
Tengo una duda, pues [en el primer test (de heurísticas)](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/tree/assignment/search/problems/nm_puzzle_test.py#L189-L203) que es para cuando hay 1 solo desplazamiento testean si es que se la heuristica da 1 (es decir hacen la distancia de manhatan para todas las casillas menos la con el número mayor que es la que vacía), lo cual hace sentido. Pero [luego](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/problems/nm_puzzle_test.py#L223) cuando testean que todas las casillas estén dadas vueltas cuentan la casilla con el número más grande, dando 24 en vez de 20 como debiera ser que la calculamos igual que antes. Por lo tanto, hacemos distancia de manhattan para las 9 casillas, o solo para las 8 moviles (llevado a cualquier slide puzzle de NxM obviamente).

**Comment by Dietr1ch** [comment]
Claro, está mal considerar ese movimiento extra. 

Puedes arreglar el test ;) 

No sé si hay una manera simple de arreglar el repo base y pasarle los cambios a todos. Voy a dejar el issue abierto por eso

**Comment by matumartinez** [comment]
Gracias por esta issue y la anterior, pensé que estaba haciendo todo mal porque los tests fallaban.

**Comment by fnberrios** [comment]
Hola! Me surgió una duda para el primer test. ¿La heurística no debería dar 2? Ya que, usando distancia manhattan y siendo el puzzle:

[0, 1]
[3, 2]

la heurística debería dar
h(3) + h(2) = 1 + 1 = 2
para obtener como solución
[0, 1]
[2, 3]

¿Estoy entendiendo algo mal?
Gracias de antemano.

**Comment by Dietr1ch** [comment]
> Hola!

Hola :p

> Me surgió una duda para el primer test. ¿La heurística no debería dar 2? Ya que, usando distancia manhattan y siendo el puzzle:
> 
> [0, 1]
> [3, 2]
> 
> la heurística debería dar
> h(3) + h(2) = 1 + 1 = 2
> para obtener como solución
> [0, 1]
> [2, 3]
> 
> ¿Estoy entendiendo algo mal?

El valor está malo, pero de otra forma. El cuadro libre es el número más alto. Entonces en ese ejemplo sólo falta mover el 2 a la izquierda, y la distancia de Manhattan sólo necesitaría considerar que el número 2 está fuera de su posición.

**Comment by fnberrios** [comment]
Ah... Comprendo! Ya genial, muchas gracias @Dietr1ch

**Comment by JuanpaBC** [comment]
Hola disculpa estoy medio perdido con la tarea y estaba revisando esta issue, pero no entendí qué hay que corregir en este caso y dónde. Agradezco cualquier orientación.

**Comment by Dietr1ch** [comment]
> Hola disculpa estoy medio perdido con la tarea y estaba revisando esta issue, pero no entendí qué hay que corregir en este caso y dónde. Agradezco cualquier orientación.



> En el primer test (de este puzzle, NM-puzzle) que es para cuando hay 1 solo desplazamiento testean si es que se la heuristica da `1` (es decir hacen la distancia de manhatan para todas las casillas menos la con el número mayor que es la que vacía), lo cual hace sentido.
>
> Pero luego cuando testean que todas las casillas estén dadas vueltas cuentan la casilla con el número más grande, dando `24` en vez de `20` como debiera ser que la calculamos igual que antes. Por lo tanto, hacemos distancia de manhattan para las 9 casillas, o solo para las 8 moviles (llevado a cualquier slide puzzle de NxM obviamente).

En la segunda parte está el problema, al calcular la heurística se estaba considerando la distancia de la casilla vacía a su posición final, pero esto es incorrecto, ya que "mover" la casilla vacía no toma acciones adicianales a las que ya se estaban contando al considerar las casillas con números/losetas/tiles.

**Comment by JuanpaBC** [comment]
Vale muchas gracias! Por lo que entendí el test queda correcto cambiando "h_values == [24, 0]" a "h_values == [20, 0]" como dijo Domingo. Si me equivoco favor avisarme.

**Comment by Dietr1ch** [comment]
> El test queda correcto cambiando `h_values == [24, 0]` a `h_values == [20, 0]` como dijo Domingo

Claro

**Comment by JuanpaBC** [comment]
Gracias!
