### ISSUE TITLE
[Tarea 2] Café/Coffee - duda sobre dominios

### ISSUE THREAD

**Issue by AlfreMK** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#123]
En realidad solo quiero asegurarme de que `connected(SrcRoom, DstRoom, Door)` es lo que pienso que es.

`connected(SrcRoom, DstRoom, Door)` es parte de las condiciones iniciales, ¿cierto?

Esto es, tener en un test case algo como
```
room(meetingRoom3).
office(o23).
door(doorOffice23).
connected(meetingRoom3, o23, doorOffice23).
```
Esto es correcto?

De antemano, gracias.

**Comment by DomingoCarvajal** [comment]
No soy ayudante pero me parece que si, es parte de la instancia.

**Comment by Dietr1ch** [comment]
> En realidad solo quiero asegurarme de que `connected(SrcRoom, DstRoom, Door)` es lo que pienso que es.
> 
> `connected(SrcRoom, DstRoom, Door)` es parte de las condiciones iniciales, ¿cierto?
> 
> Esto es, tener en un test case algo como
> 
> ```
> room(meetingRoom3).
> office(o23).
> door(doorOffice23).
> connected(meetingRoom3, o23, doorOffice23).
> ```
> 
> Esto es correcto?
> 
> De antemano, gracias.

Claro, es como el ejemplo que vimos en clases.
