### ISSUE TITLE
[Tarea 2] Café/Coffee - acciones prepare y take

### ISSUE THREAD

**Issue by AlfreMK** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#124]
Quería saber si me podía deshacer de la acción `take` puesto que considero que se podría obviar, ya que justo luego de `prepare` viene `take`. Sino es el caso, me gustaría ser proporcionado de un ejemplo en el que es necesario y el cual ahora no estoy considerando o al menos no veo.

De antemano, gracias.

**Comment by Dietr1ch** [comment]
> Quería saber si me podía deshacer de la acción `take` puesto que considero que se podría obviar, ya que justo luego de `prepare` viene `take`.

Esto no es necesariamente así, podrías tener un agente dedicado a preparar café y que los otros vayan a retirarlo y repartir.
Ahora, pensando en el caso de un solo agente, creo que tratar de agregar esta simplificación/optimización solo complica un poco más el problema y generalizarlo para varios agentes después.
