### ISSUE TITLE
[Tarea 2] - Duda con archivo input / Dependency-hell

### ISSUE THREAD

**Issue by tomasft0410** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#126]
Hola quisiera saber si en el archivo de input siempre va a existir al menos un requiresAtLeast y un requiresAtMost. O puede pasar que todos los programas tengan el mismo tipo de requerimiento. Gracias

**Comment by Dietr1ch** [comment]
Si no se dice que cumplen cierta estructura particular, entonces hay que asumir que no va a haber una.

En particular,
  * Puede haber un programa que no necesite dynamic linking.
  * Puede haber un programa que haya dejado de funcionar luego de cierta versión, y que quizás sólo especifique `requiresAtMost`
  * Y de forma análoga, puede haber una librería que asegure backwards-compatibility y se pueda especificar sólo `requiresAtLeast`.
