### ISSUE TITLE
[T3]  Seed - Numero de alumno terminado en J

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#128]
Hola, si termina en J nuestro número de alumno como lo debemos poner? En python los números terminados en J se consideran imaginarios y son permitidos por las seeds, así que ponerlo tal cual quizás igual sirva, pero sería bueno para poder dejarlo estandarizado.

**Comment by FeBalla** [comment]
Sí, pueden usar esa opción. La idea es simplemente para que tengan resultados replicables y "relativamente individuales", así que no hay ningún problema con eso
