### ISSUE TITLE
[T3] Ordenar datos 

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#129]
Hola, cuando se pide

> Ordene el dataset seg´un el nivel de ventas de menor a mayor y ocupe el primer 70 % de los datos para
entrenar un ensamble Random Forest y el otro 30 %

El ordenamiento debo hacerlo antes o después de separar los datos? Me parece que si lo hago antes podría haber cierto sesgo, ya que ni siquiera tengo alguna forma de saber que los sales más altos si quiera estén en el modelo.

**Comment by FeBalla** [comment]
El ordenamiento debe ser antes de separar los datos. Con respecto a lo demás, no te puedo dar más información ya que es parte del análisis
