### ISSUE TITLE
¿Falta info en la parte de Sokoban?

### ISSUE THREAD

**Issue by matumartinez** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#13]
Hola!

La clase State de Sokoban tiene la posición del agente y la posición de las cajas. No faltaría la posición de los objetivos? O hay algo que no estoy viendo?

**Comment by Dietr1ch** [comment]
(perdón por no contestar antes, pero como cerraste el issue pensé que no era necesario).

> La clase [State de Sokoban](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/problems/grid/sokoban.py#L45-L51) tiene la posición del agente y la posición de las cajas.
> 
> No faltaría la posición de los objetivos? O hay algo que no estoy viendo?

Claro, el Estado no sabe a cerca de cuál es el objetivo del problema, de hecho sabe nada del problema.

El espacio de estado sólo define las configuraciones posibles y sus transiciones. Es esencialmente sólo un grafo.


Los problemas (sobre un espacio de estados) definen estados iniciales (simplemente un conjunto de estados) y estados objetivos (a través de definir `is_goal(state: State)`). Para es Sudoku el problema está [acá](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/tree/assignment/search/problems/grid/sokoban.py#L291-L298).


Toda esta estructura del espacio de estados debería volverse mucho más clara luego de leer el código de [search/space.py](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/space.py).

Una vez que entiendas el espacio de estados creo que es bueno mirar [search/algorithms/search.py](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/tree/assignment/search/algorithms/search.py), que define los constructos de búsqueda que se hacen sobre los del espacio de estados (puedes ignorar `Path` o dejarlo para el final).
