### ISSUE TITLE
[T3] Cross Validation - Busqueda de hiperparámetros

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#130]
Hola, que tan exhaustiva tiene que ser la búsqueda de hiperparámetros en el cross validation? Puedo probar con varios valores, y según eso puede demorar mucho tiempo en correr el código. Además cúal debería ser el tiempo límite que debería tener para encontrar la mejor combinación?

**Comment by FeBalla** [comment]
Puedes probar con varias combinaciones, el tiempo da lo mismo, aunque evidentemente la idea es que tenga algún sentido el que se demore más, ya que quizás no valga la pena probar con un ```n_estimators = 5``` y con ```n_estimators = 6```
