### ISSUE TITLE
[T3] Reproducibilidad de resultados

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#131]
Hola, me parece que la seed que dice el enunciado no sirve de nada con Scikit-Learn. La que habría que usar es la de numpy con `np.random.seed(N)`

**Comment by FeBalla** [comment]
Sí, sklearn usa el _random state_ de NumPy, así que sí, deberían cambiar la celda que setea la _seed_ por:
```
numpy.random.seed(numero_alumno)
```

**Comment by fnberrios** [comment]
@FeBalla trate de usar el comando numpy.random.seed(numero_alumno) con mi número de alumno que termina en J y se despliega el siguiente error:

TypeError: 'complex' object cannot be interpreted as an integer

¿Elimino J?

**Comment by FeBalla** [comment]
Sí, eliminen la J o cámbiala por un **número de 2 dígitos aleatorio** (que ustedes escojan). El punto no es tanto el valor exacto de la _seed_, sino que sus resultados sean ligeramente individuales y reproducibles.

**Comment by fnberrios** [comment]
@FeBalla genial, gracias!
