### ISSUE TITLE
[T3] Librerías permitidas

### ISSUE THREAD

**Issue by fnberrios** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#132]
Hola! ¿Se permite usar pandas para ordenar los datos y eliminar información corrupta? ¿Hay algún listado de librerías que no podemos usar?
Gracias de antemano.

**Comment by FeBalla** [comment]
Sí, totalmente, todas las librerías que hemos usado en clases/ayudantías están permitidas:
* Pandas
* NumPy
* sklearn
* matplotlib
* Seaborn (para graficar)

Puede que se me quede alguna en el tintero, pero no hay problema con usar librerías. Sin embargo, si encontraran una que hiciera una parte importante del trabajo deben preguntar por una _issue_, ya que podría no considerarse la respuesta si es que usan algo que les hace todo el trabajo, pero en general no hay mayores restricciones.

**Comment by fnberrios** [comment]
Gracias!

**Comment by FeBalla** [comment]
De nada! Voy a dejar esta misma _issue_ para que pregunten en caso de que quieran consultar por alguna librería en particular

**Comment by nicoguz** [comment]
Hola,
Para la discretización de las compras podemos utilizar funciones de sklearn que lo hagan? O debemos hacerlo a mano?

**Comment by FeBalla** [comment]
> Hola, Para la discretización de las compras podemos utilizar funciones de sklearn que lo hagan? O debemos hacerlo a mano?

No hay ningún problema con usar una librería, aunque no debería hacer falta. Eso sí, debes cumplir lo de mostrar y explicar cómo se discretizaron, es decir, explicar lo que está haciendo para discretizar

**Comment by ignaciomansuy** [comment]
Hola! podemos ocupar la función `combinations` de `itertools`?

**Comment by FeBalla** [comment]
Hola!
No había alcanzado a ver el mensaje antes, pero sí, no hay problema
