### ISSUE TITLE
Duda sobre LabelEncoder

### ISSUE THREAD

**Issue by domingo2000** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#133]
Hola, dice en la actividad 2 que investiguemos sobre esta función de sklearn, y la apliquemos según corresponda, en la misma página de sklearn dice que es para variables de salida y, y no para features X, y la actividad 3 tiene que ver con pre-procesar los labels de salida. Por lo que me surge la duda de si hay que usar LabelEncoder en los features, o podemos hacerlo directamente con replace como se vió en la ayudantía?

Edit1: También leí esto que creo que apoya mi argumento 
https://stackoverflow.com/questions/59914210/why-shouldnt-the-sklearn-labelencoder-be-used-to-encode-input-data

**Comment by FeBalla** [comment]
Hola!
Por eso el enunciado dice  que la expliquen y apliquen "según corresponda" 👀 Ahora, para no confundirlos tanto, hay más de una alternativa, lo importante es que según como lo hagan lo justifiquen.

El motivo por el que se señala en la documentación que esa función que es para las variables de salida también es fácilmente corregible con algunos pasos adicionales, aunque una forma más sencilla es hacerlo como señalas.

Sea como sea, lo importante es que expliquen la función y, sea cual sea la decisión que tomen, la expliquen y justifiquen, ya que no hay una sola manera.
