### ISSUE TITLE
[T3] P1. Act4. División Training-Testing

### ISSUE THREAD

**Issue by fnberrios** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#134]
Hola! La actividad 4 de la Árboles de Decisión dice:

![image](https://user-images.githubusercontent.com/34272957/140999218-9a32c9e8-2b59-412f-be8c-f387b484cb26.png)

Me quedan dudas con la división para training y testing porque si ordeno de menor a mayor las ventas puede ocurrir que en training me queden, ejemplo, 3 clases y en testing las otras 2. Por lo cual el modelo "aprendería" solo usando algunas clases. Adjunto foto para explicar mi punto.

![39786](https://user-images.githubusercontent.com/34272957/140999066-75acc3fe-3b8f-47a9-9b16-297046a9d017.jpg)

¿Será que tendremos que dividir cada clase 70% para train y 30% para testing? ¿A eso se refieren?

Gracias de antemano.

**Comment by FeBalla** [comment]
Esto ya se respondió en #129 . Les recomiendo que lean el enunciado completo (al menos el de cada parte) para entender a qué apunta la pregunta. No puedo darles más información, ya que es parte del análisis 👀 . Yo creo que si leen las actividades que vienen les hará más sentido (no hay error en el enunciado).

**Comment by fnberrios** [comment]
Gracias
