### ISSUE TITLE
[T3] Duda Ac. 1

### ISSUE THREAD

**Issue by benjaminlillo** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#135]
Hola! En la actividad 1 se pide entregar una nueva versión del dataset. Para esto basta imprimir algunas líneas del nuevo dataset? O es necesario exportarlo como un nuevo archivo `.csv`?

**Comment by FeBalla** [comment]
Basta con que se almacene en alguna variable y mostrarlo
