### ISSUE TITLE
[T3] Predicción ventas muy altas

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#136]
Hola, cuando el enunciado dice:

> Realice una predicción únicamente sobre las instancias del set de test, cuya categorı́a corresponda
a ventas muy altas.

Se refiere que usemos las instancias con ventas muy altas como set de test?

**Comment by FeBalla** [comment]
No, se refiere a que, luego de testear con el set de test, vuelvan a testear con ese mismo set, pero utilizando únicamente las instancias que, **dentro del set de test**, correspondan a la categoría de ventas muy altas. Espero haberme explicado 😅
