### ISSUE TITLE
Duda dimensionalidad de restricciones con svm multiclase

### ISSUE THREAD

**Issue by nicoguz** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#137]
Hola!
No me queda muy claro como la cantidad de restricciones en svm multiclase es Cn - n. Entiendo que el producto punto entre los datos del set de entrenamiento con el parámetro w (Omega_k * x_i) de como resultado una matriz de n x (C - 1), pero qué ocurre con la suma con el resto de los términos? Estos deberían ser de dimensionalidades distintas o no?

**Comment by jmopaso** [comment]
Hola!

Si no te quedó tan claro con la explicación matricial, también es posible verlo de la siguiente forma. Recuerda que las restricciones en el caso del SVM multiclase son del tipo:

![image](https://user-images.githubusercontent.com/30938880/141229037-5d6cbd4d-3ba6-41fc-8b68-dc327e71ae98.png)

En la restricción vemos que tenemos una resta de entre dos elementos, el de la izquierda representa la distancia que tendrá cierto punto perteneciente a cierta clase (y_i) a su hiperplano correspondiente, mientras que el de la derecha representa la distancia que tiene **ese mismo punto**, pero ahora con el resto de los hiperplanos correspondientes a las clases distintas a y_i. Entonces si elegimos un punto cualquiera del dataset lo que deberíamos hacer es calcular la distancia a su hiperplano correspondiente y calcular la diferencia de este con la distancia del punto al resto de los hiperplanos, donde por cada hiperplano que comparo son C - 1 restricciones distintas, ya que debo comparar con todos los hiperplanos menos el propio. 

Finalmente debo ejecutar estas mismas operaciones para los n datos del dataset, quedando en n(C - 1) restricciones.

Espero que haya quedado mas claro!  Saludos
