### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#138]
En la Actividad 4 de la Primera Parte, se nos pide entrenar un modelo que utiliza Random Forest. Al correr: `y_pred = model.predict(X_test)` me aparece el siguiente error: 

**MemoryError: Unable to allocate 2.79 GiB for an array with shape (30000, 12502) and data type float64**

No sé a qué se debe o cómo solucionarlo. Gracias!

**Comment by VicenteMerino** [comment]
Tu X_test probablemente está malo, porque por el output está diciendo que tiene 30000 observaciones y 12502 features, lo cual no tiene mucho sentido porque hay como 10 en el dataset original

**Comment by ignacioarteaga99** [comment]
Hmm... no lo sé, no creo, ya que al ejecutar: 
**print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)**

Me entrega el siguiente output: 
(69999, 8)
(30000, 8)
(69999, 1)
(30000, 1)

Y al ejecutar **model.fit(X_train, y_train)**

Me entrega: **
MemoryError: could not allocate 205914112 bytes**

**Comment by FeBalla** [comment]
@ignacioarteaga99 Por casualidad, estarás usando Python de 32 bits?

**Comment by ignacioarteaga99** [comment]
![image](https://user-images.githubusercontent.com/48535635/141165391-9a69a341-3354-42fd-ae54-0033923f715e.png)

Me imagino que no, pero ya me funcionó esa parte!

**Comment by FeBalla** [comment]
Te funcionó? Podrías comentar qué cambio hiciste? por si alguien tiene el mismo problema

**Comment by benjaalfoncho** [comment]
Yo tengo el mismo problema ¿Cómo lo soluciono?
