### ISSUE TITLE
Error al ejecutar cross_val_score

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#139]
Al ejecutar el siguiente código: 
**r2 = cross_val_score(model, X_train, y_train, scoring='r2', cv=5)**

De output me aparece el siguiente error: 
**UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.**

He investigado pero no entiendo muy bien cómo solucionarlo. Gracias!

**Comment by FeBalla** [comment]
Probablemente tenga que ver con cómo separaste las _features_ de la _label_, ya que tu vector ```y``` debería ser un arreglo unidimensional. Prueba haciendo
```
print(y.shape)
```
y ve qué dimensiones tiene esa variable

**Comment by ignacioarteaga99** [comment]
Al ejecutar:
**print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
**

De output tengo:
**(69999, 8)
(30000, 8)
(69999,)
(30000,)**

Los vectores _y_ son unidimensionales

**Comment by FeBalla** [comment]
Las dos cosas más probables:
* El arreglo ```y``` no es exactamente como debería de ser (dimensiones, formato, o algo por el estilo)
* En el arreglo ```y``` te está apareciendo un valor asociado a una categoría, pero que aparece solamente 1 vez
Partiría por revisar bien la dimensionalidad y ver cuáles son los valores únicos que hay en ese arreglo (y cuántas veces aparece cada uno)

**Comment by VicenteMerino** [comment]
Creo que es por la cantidad de atributos en una clase, quizas en la clase ventas muy altas tienes  solo 1 elemento. A mi me paso lo mismo y lo solucione haciendo una separacion mejor.

**Comment by FeBalla** [comment]
> Creo que es por la cantidad de atributos en una clase, quizas en la clase ventas muy altas tienes solo 1 elemento. A mi me paso lo mismo y lo solucione haciendo una separacion mejor.

Claro, ese es el motivo "real" por el que se arrojaría este error, aunque se puede dar a veces por temas de dimensionalidad (no sé bien por qué). 

El tema es que, si siguen las instrucciones, es muy extraño que haya una categoría que les aparezca solo 1 vez en training. Podría ser que haya una categoría que no les aparezca, pero que les aparezca una vez es un poco extraño la verdad 😕

**Comment by ignacioarteaga99** [comment]
Hmm ya, con lo que han dicho me entró una duda: ¿Tenemos que trabajar con el dataset con las ventas ya clasificadas o no? Vale decir, como lo dejé en la actividad 3. Pensé que debía ser con las ventas tal cual estaban. Si es así por favor confirmar, gracias!

**Comment by ignacioarteaga99** [comment]
Lo probé con el dataframe ya categorizadas las ventas y me funcionó bien btw!! Gracias!

**Comment by FeBalla** [comment]
> Hmm ya, con lo que han dicho me entró una duda: ¿Tenemos que trabajar con el dataset con las ventas ya clasificadas o no? Vale decir, como lo dejé en la actividad 3. Pensé que debía ser con las ventas tal cual estaban. Si es así por favor confirmar, gracias!

Te pido que lo preguntes en otra _issue_ por favor, para que el título quede claro y con gusto te respondo 😄
