### ISSUE TITLE
Sokoban: contar acciones

### ISSUE THREAD

**Issue by matumartinez** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#14]
Hola!

Para la parte de Sokoban en la cual dice: "Notando que el agente tiene que acercarse a las cajas es fácil notar que falta contar acciones. Implemente esta versión mejorada de la heurística." No entiendo bien que quiere decir con "acciones". Se refiere a la cantidad de movimientos que debe hacer el agente para desplazar una caja una posición?

Saludos

**Comment by Dietr1ch** [comment]
Claro, las acciones del problema son caminar en alguna dirección, o empujar una caja en alguna dirección.
