### ISSUE TITLE
Duda Actividad 4

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#141]
Hola! Una duda: ¿Tenemos que trabajar con el dataset con las ventas ya clasificadas o no? Vale decir, como lo dejé en la actividad 3. Pensé que debía ser con las ventas tal cual estaban. Si es así por favor confirmar, gracias!

**Comment by sperezmasri** [comment]
Hola @ignacioarteaga99! En la actividad 4 deben trabajar con el dataset nuevo, es decir con las ventas ya clasificadas, saludos 😁
