### ISSUE TITLE
Duda Actividad 5

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#142]
Se nos pide hacer una buena división de los datos para entrenamiento y test, por lo que me surgen unas dudas: ¿Esta división corresponde al `test_size` o corresponde a la división de la clasificación de ventas realizadas en la actividad 3? ¿Se debe hacer con el último dataframe obtenido en la actividad 4 (vale decir sólo con ventas muy altas)?

Pregunto esto también porque ya tuve un accuracy score sobre el 70% de rendimiento y no sé en verdad si puedo o cómo seguir mejorandolo.
Gracias!

**Comment by sperezmasri** [comment]
Hola @ignacioarteaga99! La división se refiere a dividir los datos en dos sets (_test_ y _train_), tu tienes que ver cuál sería una buena división (qué proporción de los datos asignar a cada set) según lo que sabes . Con respecto a tu segunda pregunta, se debe hacer con los datos que contengan todas las ventas no solo las ventas muy altas, es decir, el dataframe resultante de la actividad 3.
