### ISSUE TITLE
[Tarea 3] Duda SVM

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#143]
Hola, me queda la duda por qué en la función de pérdida o costos (problema relajado), el w0 desaparece?
![image](https://user-images.githubusercontent.com/47841749/141654755-e5748795-d4de-47d2-a628-5c0403e2c8bc.png)

![image](https://user-images.githubusercontent.com/47841749/141654740-76967f42-c52a-419a-b053-78bfcb44e557.png)

O es solo que al final lo podemos despreciar si nos quedamos con los valores >=0?

**Comment by jmopaso** [comment]
Hola Vicente, es una excelente pregunta. La respuesta está en que nunca en realidad influye el `w0` en la función objetivo del problema de optimización (que al final define la función de pérdida para el descenso de gradiente), sino que sólo influye en las restricciones de este. 

Recuerda que el problema de optimización para SVM busca maximizar el margen `M` entre los vectores de soporte y el hiperplano, sin embargo nosotros realizábamos un cambio de variable en donde decíamos que `M = 1/||w||` con esto nos quedaba un problema del tipo `max 1/||w||` lo que es equivalente a `min ||w||`.
