### ISSUE TITLE
Informe con respuestas a las preguntas

### ISSUE THREAD

**Issue by MTSuarezS** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#144]
Hola, me gustaría saber si para esta tarea se debe crear un informe que se suba en pdf con las respuestas a las preguntas, y las explicaciones de cada actividad, o si es posible que subamos esto en el mismo jupyter notebook.

**Comment by sperezmasri** [comment]
Hola @MTSuarezS! Las respuestas a las preguntas y las explicaciones de cada actividad **deben** ir en el mismo jupyter notebook donde estas desarrollando el código, es decir se entrega un único archivo, saludos 😁

**Comment by MTSuarezS** [comment]
Buenisimo! gracias
