### ISSUE TITLE
[Tarea 3] Implementación SVM 

### ISSUE THREAD

**Issue by mscuturrufo** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#145]
En la actividad 2 de la parte del SVM, ¿debemos implementar el SVM multiclase como se planteó en la ayudantía  o puede ser de otra forma?

**Comment by jmopaso** [comment]
Hola! No es estrictamente necesario, pero si altamente recomendado.

Saludos!

**Comment by mscuturrufo** [comment]
Gracias!

**Comment by mscuturrufo** [comment]
Gracias!
