### ISSUE TITLE
Actividad 2-Df

### ISSUE THREAD

**Issue by Mjtala** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#148]
En la actividad 2 el cambio de labels tiene que quedar reflejado en el dataframe original o podemos hacer un nuevo dataframe para cada dataframe que codifiquemos. 
Muchas gracuas

**Comment by FeBalla** [comment]
Eso queda totalmente a decisión de ustedes, aunque ojo con guardar mucha información si es que no es estrictamente necesario, más que nada para evitar problemas de RAM y eso :)

**Comment by Mjtala** [comment]
Muchas gracias!
