### ISSUE TITLE
[T3] Actividad 1 - Limpieza de datos

### ISSUE THREAD

**Issue by benjaalfoncho** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#149]
Hola, en cuanto a la limpieza de datos del dataset entregado ¿Qué elementos de los datos pueden estar con errores o inconsistencias? Me puse a buscar inconsistencias mas no encontré nada, pero dudo que no haya nada dado lo que dice el enunciado. ¿Podrían especificar más cuál es el trabajo en esta parte? Gracias!!

**Comment by FeBalla** [comment]
Hola!
El enunciado dice cosas generales que pueden ocurrir en una situación real. Dada la descripción del _dataset_ deberían saber qué _features_ son relevantes, cuáles no (ya sea por redundancia o que no aportan información). También deberían ver cómo abordar los errores típicos de datos incompletos, etc.

Entiendo que tu duda apunta a si dejamos alguna fila con errores muy rebuscados, como poner ventas negativas o algo. Sobre eso, la verdad es que no. No está hecha con malicia la pregunta, así que pueden estar tranquilos/as/es
