### ISSUE TITLE
[Control 2] Duda optimalidad w-A*

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#15]
Hola tengo una duda, sobre w-A*. Segun lo que dice acá no debería ser w < 1 para que sea mas barata la solucion? Ya que dice que produce una solucion no mas de w veces mas cara que la solucion optima.

![Screenshot from 2021-09-13 21-03-10](https://user-images.githubusercontent.com/47841749/133172906-aaa1a3ce-4edb-4ed4-9c32-98e362187c05.png)

**Comment by Dietr1ch** [comment]
w-A* con w>=1 produce soluciones que cuestas a lo mas w veces el costo óptimo.

Por ejemplo, con w=2 puedes obtener una solución que cueste no más del doble del óptimo. Puede ser mejor, pero no tienes cómo saber.


Los pesos entre 0 y 1 son difíciles de interpretar bien, además que las soluciones obviamente no van a volverse mejores que óptimas.

**Comment by Dietr1ch** [comment]
BTW, algo interesante de probar en esta tarea es implementar w-A*, iba a ser parte de la tarea, pero pensé que podía quedar muy larga.

Una vez que termines A*, puedes copiar el archivo y cambiar 1 línea para volverlo w-A* y probar cómo se comporta con el main que ya tiene listo la tarea.
