### ISSUE TITLE
Actividad 4: Orden de los datos.

### ISSUE THREAD

**Issue by DomingoCarvajal** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#151]
En la actividad 4 se nos pide que ordenemos los datos según el nivel de ventas para hacer la separación. 
En la actividad 3 se nos pide que definamos categorías discretas del nivel de ventas. Debemos ordenar según esta categoría? o hay que ordenar según los datos de ventas iniciales? 
El resultado sería diferente ya que habrían muchos empates en la discretización que se ordenaran aleatoriamente, en vez de siguiendo el  orden del número de ventas inicial.

**Comment by FeBalla** [comment]
Debes ordenar en base a los resultados discretizados, por lo que lo de los empates es irrelevante
