### ISSUE TITLE
[Tarea 3][2.1] Duda función costo

### ISSUE THREAD

**Issue by cjones27** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#152]
Hola! No sé si sea importante, pero en la implementación de SVM la función costo tiene definida la norma así

`norm = (self.params**2).sum()        # 1. Norma de los parámetros (||B||)`

Creo que le falta la raíz cuadrada. Esto afecta el resultado? Como para modificarlo o no.

Gracias!

**Comment by jmopaso** [comment]
Hola Cristobal! Bien notado! Pero si te fijas no es relevante porque la función de costo es la siguiente:
![image](https://user-images.githubusercontent.com/30938880/142336958-41dbed64-ec72-4611-b00c-dc1baa088d02.png)

Donde tenemos `||w||^2` que es lo mismo que la variable `norm` sin aplicarle la raíz cuadrada, si te fijas en lo que retorna la función simplemente se ocupa `norm/2` que es lo mismo que `||w||^2/2`.

Saludos!
