### ISSUE TITLE
Actividad 3: Formas de discretizar los datos.

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#153]
Hola!

Me gustaría saber qué tanta libertad tenemos sobre el criterio para discretizar los datos, ya que el hecho de que se nos pida un histograma me hace pensar que se requiere separar las ventas por intervalos del mismo tamaño (no frecuencia), tomando en cuenta el rango entre la venta más baja y la venta más alta. Personalmente, me gustaría trabajar con otro tipo de discretización, por lo que me gustaría saber si es posible entregar un gráfico de barras que cumpla con el criterio que quiero aplicar.

Desde ya muchas gracias c:

**Comment by FeBalla** [comment]
Hola!

Son totalmente libres. El histograma en particular es para dejarnos claro de forma explícita y visual cuál fue la distribución que utilizaron, lo importante es que expliques por qué te quedaste con esa opción 😄

**Comment by FeBalla** [comment]
Sí, quizás escogimos mal el término. La verdad es que esperamos justamente un gráfico de barras más que un histograma agrupado, aunque dada la cantidad de categorías tampoco tiene sentido agrupar (hay solo 5). Al fin y al cabo, lo que necesitamos es poder ver cuántas instancias quedaron por categoría.

**Comment by Sofia-Arratia** [comment]
Perfecto, muchas gracias! Que tengas un buen día c:
