### ISSUE TITLE
[T3] Actividad 4: Justificación rendimiento clasificador en el set de entrenamiento y en el set de test

### ISSUE THREAD

**Issue by Meaylwin** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#154]
Hola! 😄 
En la primera pregunta de la actividad 4 dice "¿Qué puedes decir del rendimiento del clasificador en el set de entrenamiento y en el de test?"
Entiendo que para ver el rendimiento en el set de test puedo usar la función *accuracy_score* dandole como parametros el dataset y_test y la prediccion de x_test
Entonces, para ver el rendimiento del set de entrenamiento, ¿puedo hacer lo mismo entregandole a *accuracy_score* el y_train y la predicción del x_train?

No se si eso es lo que se espera de esa pregunta
Muchas gracias!

**Comment by FeBalla** [comment]
Sí, es algo así lo que estamos esperando que evalúen y por sobre todo **analicen**

**Comment by Meaylwin** [comment]
Muchas gracias! Puedes cerrarla
