### ISSUE TITLE
Actividad 4. División en train y test.

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#156]
Hola!

Entiendo que debemos ordenar los datos según la división de la Actividad 3, pero para utilizar después cross validation tenemos que usar generadores acordes a ellos. De las issues que he leido no me queda claro todavía si en la división entre train y test está permitido "revolver" los datos, porque en el caso específico de generadores para cv, si no lo hago quedarían n folds iguales, y el cv perdería su propósito. Traté de explicar lo menos posible la materia con mi pregunta, perdón si di mucha información.

Gracias de antemano!

**Comment by Sofia-Arratia** [comment]
Hola! Me resolvieron la duda en la sala de ayuda. Muchas gracias!

**Comment by FeBalla** [comment]
Hola!
No sé si me quedó muy clara la pregunta, así que sería genial si pudieras dejar la respuesta acá igual. Sin embargo, lo que estamos pidiendo es que en entrenamiento ocupes el primer 70% de los datos, obteniéndolos por indexación o como les salga más sencillo y a `cross_val_score` le pasan ese mismo set para probar los hiperparámetros 😄
