### ISSUE TITLE
[T3] Actividad 5 parte b accuracy

### ISSUE THREAD

**Issue by acastill20** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#157]
Hola, en la actividad 5 en la primera parte me esta dando más de 70% de accuracy, mientras que en la parte b donde piden realizar una predicción utilizando ventas muy altas me da 65%. En el enunciado establecen que debe dar 70% en la primera parte pero no hablan de una minima cantidad de accuracy en la predicción de ventas muy altas pero por si acaso quería preguntar si es necesario que la parte B tenga también más de 70%.

**Comment by FeBalla** [comment]
El requisito es que en el set de test completo en la actividad 5 tengan más de un 70% de _accuracy_, así que por lo que te entendí, no deberías tener ningún problema 😄

**Comment by acastill20** [comment]
Me refiero a que en la pregunta en si establecen que el accuracy del nuevo random forest debe ser de mayor de 70% para obtener el puntaje. Aqui si tengo sobre 70%. Sin embargo, abajo de esta instruccion en el tercer punto dicen "Realice una prediccion unicamente sobre las instancias del set de test, cuya categoria corresponda a ventas muy altas. Evalue la exactitud del modelo y comente que esta sucediendo." Aqui me esta dando una accuracy de 65% entonces no estoy seguro si lo de obtener más de 70% es para toda la actividad 5 o solo para el ejercicio inicial.

**Comment by FeBalla** [comment]
No, no es necesario, porque el 70% mínimo es sobre el set de test en general, no sobre el subconjunto con la categoría de ventas muy altas, así que estás bien
