### ISSUE TITLE
Duda: Árboles de decisión

### ISSUE THREAD

**Issue by jtcaraball** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#158]
Hola! 
Puede un árbol de decisión tener una profundidad mayor a los features que se usan para entrenarlo? La clase DecisionTreeClassifier de sklearn me genera un árbol de profundidad 10 a partir de 6 features y me confunde un poco. Me siento tentado a pensar que si se decide una única vez sobre n features llegar a un nodo hoja no debería tomar más de n nodos.

Muchas gracias!! :D

**Comment by FeBalla** [comment]
Hola!
Excelente pregunta. La verdad es que la respuesta dependerá de la implementación particular de sklearn y me atrevería a decir que si le das un valor mayor, lo truncará. Una forma de quitarte la duda podría ser probando con profundidad 10 y, por ejemplo, 20. En teoría, no deberían haber diferencias, salvo que por debajo esté haciendo algún proceso adicional cuando se sobrepasa el valor de la cantidad de _features_
