### ISSUE TITLE
Duda Bonus

### ISSUE THREAD

**Issue by OrregoSilva** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#159]
Hola! En el bonus, cuando dicen que A3 debe usar las instancias que fallaron en clasificar, lo hago considerando el mismo set de train? Osea, tengo un árbol (1 o 2), lo entreno con un set X de datos, y luego predigo usando el mismo set X y las filas que fallan se usan en A3?

**Comment by FeBalla** [comment]
Sí, porque eso es parte del metodo `fit` (o `train`, no recuerdo qué nombre les pedimos 😄) y a ese se le pasa el set de entrenamiento (`X`) con sus respectivas _labels_ (`y`). Entonces, el primer árbol escoge algunas _features_ de _X_, el árbol 2 escoge todas las que no escogió el primero y, por último, el tercero las ocupa todas, pero se entrena únicamente con las instancias en las que alguno de los primeros 2 haya fallado.
