### ISSUE TITLE
[Tarea 1] Implementación Sokoban

### ISSUE THREAD

**Issue by domingo2000** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#16]
Hola, estaba cambiando la entrada del metaproblema de sokoban en el código y por alguna razón siempre me reconoce solamente una "G" de las ingresadas en la grilla como goal y no todas. Será un bug del programa? o estoy haciendo algo mal?. Adjunto imagenes
![image](https://user-images.githubusercontent.com/40220174/133174282-c8917c7c-1abc-4277-9c01-25e1fb5fd584.png)
![image](https://user-images.githubusercontent.com/40220174/133174328-e917269c-21c0-4a82-8e9f-32e5f038cfa9.png)
![image](https://user-images.githubusercontent.com/40220174/133174370-f24e6579-15e2-4d42-9403-42af467a0cca.png)
Además aprovecho de preguntar, supongo que S, B y G son el agente, las cajas y los goals respectivamente, pero que son los signos de exclamación en la grilla?

**Comment by Dietr1ch** [comment]
Es un problema de la implementación de SokobanMetaProblem.

La implementación de `simple_given` es la que usan todos los problemas, pero la verdad
es que tener un sólo objetivo no funciona bien en la práctica, ya que tiende a generar
problemas sin solución (y muchos).

La solución, hacer que [`SokobanMetaProblem::simple_given`](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/problems/grid/sokoban.py#L442-L446) simplemente retorne `iter([])`.



Para la segunda pregunta, los signos de exclamación son cajas y objetivos
([Acá está la definición de los símbolos](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/problems/grid/sokoban.py#L385-L393), el parser está un poco más abajo.
