### ISSUE TITLE
Duda código base SVM

### ISSUE THREAD

**Issue by nicoguz** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#160]
Hola!

En la función `calcular_gradiente`, no entiendo por qué le multiplican `valid_sample` cuando en la fórmula presentada antes dice simplemente `y_i * x_i`, y por qué le aumentan la dimensionalidad a `valid_sample` para que sea una matriz con columnas iguales.

![image](https://user-images.githubusercontent.com/53801690/142903350-53501a70-90ed-4dcf-9a63-61b368403cf5.png)
![image](https://user-images.githubusercontent.com/53801690/142903417-0620fbe2-2c1f-427a-b7fd-b7fc91211c2d.png)

**Comment by jmopaso** [comment]
Hola! 

Muy buena pregunta, si te fijas en el código, tanto para el caso de la función de costo como para el gradiente sólo se consideran los datos que están mal clasificados (aquellos con `dist > 0`) ya que son estos los que yo quiero realmente mejorar o minimizar. En el caso que me muestras `valid_sample` en un principio representa un vector de 0s y 1s que indica si un punto esta bien (0) o mal clasificado (1), luego se le aumenta la dimensionalidad para poder multiplicarla por Y y X, tal y como se indica en la formula. 

Finalmente lo que pasa es que se calcula la suma de los `y_i * x_i`, pero sólo de los que están mal clasificados, ya que los que estén bien clasificados estarán multiplicados por cero gracias al valid_sample.

Saludos!
