### ISSUE TITLE
T3 funcion de costos

### ISSUE THREAD

**Issue by mmontecino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#161]
Hola tengo una duda con el llamado a funcion_costo en el BinaryClassifierSVM, dado que al entrenar llama a esta funcion y guarda los valores en variables que no se utilizan, por lo que mi duda esta en que si son realmente necesarios dado que la minimización o maximización se genera en el descenso de gradiente para ver si lo implemento de igual manera o diferente en el multiclase

**Comment by jmopaso** [comment]
Hola! Como bien señalas esas variables no son ocupadas, por lo que podrías omitirlas, queda a tu criterio. Ojo nomás la función de costo se ocupa también para el método `hyperplane_plot`.
