### ISSUE TITLE
[T4] Actividad 3 - Análisis de las imagenes

### ISSUE THREAD

**Issue by Mjtala** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#163]
Hola!
Cuando nos piden analizar las imágenes, podemos guiarnos de las características que aparecen en tensorFlow o tenemos que hacer un análisis más al ojo?

**Comment by FeBalla** [comment]
Todo análisis es válido, siempre y cuando esté **bien explicado y justificado**. En este caso, si el proveedor de los datos (TensorFlow) les dice cierta información, pues también es útil, aunque valoramos que se animen a dar su apreciación personal
