### ISSUE TITLE
Carpeta convolution_tests actividad 2

### ISSUE THREAD

**Issue by MTSuarezS** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#164]
Hola,

No me queda claro de donde debo obtener la carpeta convolution_tests para realizar la actividad 2, pues no viene en los archivos entregados.

**Comment by FeBalla** [comment]
Hola!
Se me pasó subirla al inicio, pero las pueden encontrar en el [repositorio de la tarea](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Assignment-4/tree/78174f2f5558fd8b0442edc41296accadf6df9b1) (ojo que **no se les actualizará si ya crearon sus repositorios**, así que deben descargar la carpeta). En todo caso, las imágenes **no tienen absolutamente nada de especial** (pueden usar cualquiera), solo tienen la gracia que son las del enunciado 😄
