### ISSUE TITLE
[ Tarea 4 ] Actividad 2 - ¿Kernel incorrecto?

### ISSUE THREAD

**Issue by jiaranda** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#166]
Hola! En la actividad 2 se nos pide que trabajemos con unos kernels específicos, pero al aplicar la convolución, uno de los kernel siempre me entrega una imagen difusa. Es posible que el kernel esté mal definido en el enunciado? o soy yo el que está haciendo algo mal? Les dejo mis resultados al aplicar la convolución a la imagen de Thor.

Si se fijan, la segunda imagen (el kernel k2 del enunciado), se deforma por completo.

![thor_0](https://user-images.githubusercontent.com/26118758/143818073-e038fcdf-3028-405b-8a2b-1e13583c4062.png)
![thor_1](https://user-images.githubusercontent.com/26118758/143818075-a3f6f9cf-9310-405d-a958-7c9f0851acb8.png)
![thor_2](https://user-images.githubusercontent.com/26118758/143818076-a26b9f0c-90d1-4031-b172-554fb9f8dc24.png)

**Comment by FeBalla** [comment]
Hola, acabo de verificar y los _kernels_ son correctos, así que probablemente sea un detalle de tu implementación, aunque no debe ser algo tan grave porque los resultados en las fotos 1 y 3 ya son bastante cercanos 😄
