### ISSUE TITLE
Resultado extraño al pasar imagen a gris

### ISSUE THREAD

**Issue by matumartinez** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#167]
Hola!

Al pasar una imagen a escala de grises me ocurre lo siguiente: 

<img width="225" alt="Captura de Pantalla 2021-11-29 a la(s) 19 06 19" src="https://user-images.githubusercontent.com/42516267/143954190-b5edb5ec-2ba9-4af0-96de-53dbeb180f15.png">

¿Por qué pasa eso? Estoy usando PIL para abrir la imagen.

Saludos

**Comment by FeBalla** [comment]
Eso es normal, porque finalmente al pasar a escala de gris lo que en realidad estás haciendo es pasar de 3 canales (RGB) a 1. Lo que te dirá qué colores tiene es el _colormap_ que uses al graficar, que en este caso debería ser gris. 

Dicho esto, para graficar y que se muestre en gris, tu línea debería quedar algo así:
```
plt.imshow(img, cmap="gray")
```
