### ISSUE TITLE
[Tarea 4] Librerias permitidas y calculo de convolucion

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#168]
Hola, para calcular la convolucion debemos hacerlo a mano? En particular queria saber si puedo usar `scipy.ndimage.convolve`

**Comment by FeBalla** [comment]
Hola, **tiene que ser "a mano"**, programando el algoritmo que se describe en la cápsula, ya que la idea es que se familiaricen y experimenten 😃
