### ISSUE TITLE
[Tarea 4] Uso de colores

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#169]
Hola, no me queda claro si es necesario efectivamente usar los otros colores, aparte de la escala de grises en la imagen, o solo decir si podría aportar información? Tengo este problema, porque cuando uso varios colores (RGB, gris y una mascara) se me llena toda la memoria al ir guardando tantas matrices. No se de que forma podemos trabajar esto? O si hay alguna forma de pedir más memoria a colab.

**Comment by FeBalla** [comment]
Hola, no sé si estás hablando de la parte de la convolución o ya en la red neuronal convolucional. Para la convolución no es necesario que usen el RGB, pueden trabajar en escala de grises. Por otra parte, para el set de malaria, esperamos que ustedes vean el _dataset_ y se pregunten:
> - ¿Se siguen entendiendo las imágenes si quito los colores?
> - Para distinguir entre perros y gatos yo no necesito el color, ¿para distinguir entre células infectadas o sanas necesito el color?
> - ¿Es el color algo fundamental para saber si la célula está infectada o es más bien secundario? ¿Cómo distingo si una célula tiene el parásito?

A partir de esto, será decisión de ustedes si trabajar en RGB o en escala de grises. En la parte de código están bastante acompañados/as/es con las cápsulas, ya que creemos que estos razonamientos a lo largo de la tarea son lo fundamental (lo mismo en las transformaciones de aumento de datos). En cuanto al espacio en memoria, tienen un montón de opciones:
* Reducir el tamaño de las imágenes
* Usar menos imágenes (ojo con la representatividad del set)
* Liberar memoria basura
* Trabajar por referencia

Espero esto responda tu pregunta
