### ISSUE TITLE
[control 2]

### ISSUE THREAD

**Issue by crvargasu** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#17]
Hola, una duda respecto al control 2. En la pregunta 7
![Screenshot from 2021-09-13 21-52-08](https://user-images.githubusercontent.com/48322767/133176186-9afeefcc-5ecd-4dcf-add7-ae0e1fa2a5db.png)
Tenia entendido que no se exploraban todas las hojas del árbol, de hecho en la ayudantía nos mostraron este ejemplo donde prescisamente no se exploran todas las opciones.

![Screenshot from 2021-09-13 21-51-39](https://user-images.githubusercontent.com/48322767/133176237-16351868-ca4a-4399-8734-03528781a735.png)
Por lo que no entiendo por qué es correcto que se exploran todas las decisiones posibles

**Comment by Dietr1ch** [comment]
No confundir Minimax con Poda Alfa-Beta.

Minimax no poda el árbol, y sólo resuelve el valor de los nodos en los estados finales.

Poda Alfa-Beta es el algoritmo que aprovecha de podar ramas que no van a ser jugadas al notar que el adversario tiene una opción que le asegura un mejor valor. En principio es lo única optimización que hace y también necesita alcanzar estados finales para resolver su valor, pero una vez que se presenta Poda Alfa-Beta es natural empezar con las otras optimizaciones (estimar valores a cierta profundidad, ordenar las acciones para hacer la poda de alfa-beta más eficiente, y descartar acciones que son muy malas).
