### ISSUE TITLE
Parametros a recibir en simple_2d_convolution

### ISSUE THREAD

**Issue by nicoguz** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#170]
Hola!
En la actividad 2, al crear la función `simple_2d_convolution` ¿Podemos asumir que el parámetro `image` es un path a una imagen y `kernel` es una lista (a diferencia de otro objeto como un numpy array)?

**Comment by FeBalla** [comment]
Lo ideal es que trabajen `img` como la matriz de píxeles de la imagen, pero también pueden trabajarlo como path, siempre y cuando quede claro en alguna parte y pongan ejemplos 😄
