### ISSUE TITLE
Google Colabs  y GitHub

### ISSUE THREAD

**Issue by cncosta** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#171]
Hola estoy tratando de sincronizar Colab con mi repositorio de GitHub para la tarea 4, pero al no ser mío necesito autorización del curso. ¿Es posible hacer esto y que solo tenga acceso a mi repositorio?
Lo pregunto porque al parecer solicité acceso a todo el repositorio.

**Comment by FeBalla** [comment]
Realmente, la forma más sencilla es que trabajes en Colab y después descargues el archivo como .ipynb 😄

**Comment by cncosta** [comment]
Si me tincaba, Gracias!
