### ISSUE TITLE
T4 Actividad 7 parte 1

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#172]
Tengo un problema cuando aplico un aumento de datos mediante ImageDataGenerator. Al aplicar transformaciones del tipo "range" (shear_range, zoom_range, width_shift_range, etc) me aparece el siguiente error:

AxisError: axis 2 is out of bounds for array of dimension 2

No entiendo bien qué debería cambiar para que funcione. Gracias!

**Comment by FeBalla** [comment]
Hola!
Es un problema particular de tu código, la verdad tendría que ver bien cómo estás manejando el _dataset_ antes. Si es por traducirte el error (aunque es evidente), te está diciendo que las dimensiones de tu arreglo son incorrectas, pero está complejo saberlo sin más información. Podrías revisar bien si tu _dataset_ es lo que debería ser, buscar en StackOverflow o intentar contactarnos por la sala de ayudas en Discord (estamos hasta las 11:30, aunque quizás haya algún ayudante disponible después).

**Comment by FeBalla** [comment]
Como no hay nueva actividad, cerraré la _issue_ por ahora
