### ISSUE TITLE
Train test split en tarea 4 parte 1

### ISSUE THREAD

**Issue by Coolgatty** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#173]
Al usar train_test_split se cae el jupyter por falta de RAM. Asumo que es por que tengo cargadas todas las imagenes pero como podria hacer el train_test_split si lo cargo en batches? Ademas, no se como cargar el dataset en batches :)

**Comment by FeBalla** [comment]
Hola, estamos en Discord respondiendo dudas personales hasta las 11:30. No te sabría decir bien el motivo, ya que el manejo de memoria que hicimos nosotros no es particularmente eficiente y no tuvimos ningún problema en Colab, ni siquiera usamos batches. Lo que te diría es que tengas cuidado con almacenar muchas veces el _dataset_ y si defines un arreglo de numpy trabajes con `np.zeros` y luego vayas añadiendo los valores (para que se añadan por referencia) en vez de append.

**Comment by FeBalla** [comment]
Como no hay nueva actividad, cerraré la _issue_ por ahora
