### ISSUE TITLE
Tarea 4 parte 2 get_state

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#174]
El enunciado de la Tarea 4 señala que la función get_state() retorna una tupla de 0 y 1, sin embargo, me está retornando una tupla de Trues y Falses, es problema de mi código o qué onda? Paso esos valores booleanos a 0 y 1?

Gracias!

**Comment by vicentevegaulloa** [comment]
Hola @ignacioarteaga99!

Tu código está bueno, el `get_state` retorna una tupla de booleanos. Da lo mismo si transformas los booleanos a 1 y 0, lo importante es que logres identificar los diferentes estados del problema y trabajes con ellos.
