### ISSUE TITLE
[Tarea 4] Gráficos en actividad 5

### ISSUE THREAD

**Issue by benjaminlillo** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#175]
Hola! Para los gráficos que piden en la actividad 5 de la parte 1 del accuracy y loss function, ¿Basta con mostrar el tensorboard con los gráficos? ¿O debemos graficarlos de otra forma que no dependa de la extensión?

**Comment by FeBalla** [comment]
Deben **mostrarlos de forma que no dependa de la extensión**, porque esa extensión es de Colab y al descargarlo nosotros no veremos esos gráficos. En todo caso, es muy sencillo hacer el mismo gráfico, con una googleada aparece 😃

**Comment by benjaminlillo** [comment]
Yap gracias!
