### ISSUE TITLE
[Tarea 4] Parte 1 Act 2 Resultado convoluciones

### ISSUE THREAD

**Issue by sofiaolmedos** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#176]
Hola! Quería saber si se espera que las convoluciones en esta parte se vean como las del enunciado. En mi caso no me dan tan 'lisas' o 'claras' como las del enunciado.
Así se ven las mías
![Captura de pantalla (1)](https://user-images.githubusercontent.com/69520545/144753757-202fdd2c-cd44-4858-bfed-88c9ce50e0ee.png)

**Comment by FeBalla** [comment]
Hola! Probaste a estandarizar los valores de la imagen antes de pasarla por la convolución, es decir, dividir la matriz de píxeles por 255?

**Comment by sofiaolmedos** [comment]
> Hola! Probaste a estandarizar los valores de la imagen antes de pasarla por la convolución, es decir, dividir la matriz de píxeles por 255?

Para esta parte no. Lo voy a intentar. Gracias!

**Comment by FeBalla** [comment]
Al final, para quienes tengan una situación similar, puede servirles estandarizar (dividir por 255) y recuerden agregar el `cmap="gray"` al usar `plt.imshow`, es decir:
```
plt.imshow(convoluted_img, cmap="gray")
```
