### ISSUE TITLE
[Tarea 4] ImageDataGenerator 

### ISSUE THREAD

**Issue by Coolgatty** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#177]
Cuanto trato de usar rotation_range o zoom_range en el imagedatagenerator y luego hacer generator.random_transform me tira el error:

```
AxisError                                 Traceback (most recent call last)
<ipython-input-62-973249f83cdf> in <module>()
----> 1 newex = generator.random_transform(ex)
      2 plt.imshow(newex, cmap="gray")

3 frames
<__array_function__ internals> in rollaxis(*args, **kwargs)

/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py in rollaxis(a, axis, start)
   1289     """
   1290     n = a.ndim
-> 1291     axis = normalize_axis_index(axis, n)
   1292     if start < 0:
   1293         start += n

AxisError: axis 2 is out of bounds for array of dimension 2
```

**Comment by FeBalla** [comment]
Hola! Ya tuvimos esta duda en otra _issue_, pero la verdad es que es un poco complejo sin poder ver lo que has hecho. Por muy evidente que sea, lo que te podría decir es que es probable que tu _dataset_ no sea lo que crees que es o lo que debería ser según trabajamos en las cápsulas.

Podría ser algún tema de dimensiones, de cómo lo definiste, etc. Lamento no poder darte mucha información más útil, pero es más un tema de debuguear que de algo que no hayamos visto/mencionado 😢

**Comment by Coolgatty** [comment]
> Hola! Ya tuvimos esta duda en otra _issue_, pero la verdad es que es un poco complejo sin poder ver lo que has hecho. Por muy evidente que sea, lo que te podría decir es que es probable que tu _dataset_ no sea lo que crees que es o lo que debería ser según trabajamos en las cápsulas.
> 
> Podría ser algún tema de dimensiones, de cómo lo definiste, etc. Lamento no poder darte mucha información más útil, pero es más un tema de debuguear que de algo que no hayamos visto/mencionado 😢

Pucha de verdad queria aplicar rotaciones y zoom pero no me funciono. Te juro que busque mucho pero no me encontre el problema en ninguna parte. Igual sin eso me funciona bien el modelo pero fome hacer solo flips.

**Comment by FeBalla** [comment]
Te recomendaría seguir probando **más adelante**, porque igual evaluaremos que apliquen al menos un par de transformaciones, además de que la mejora en el rendimiento suele ser notable, pero por ahora mejor sigue avanzando con el resto de la tarea 👍

**Comment by Coolgatty** [comment]
> Te recomendaría seguir probando **más adelante**, porque igual evaluaremos que apliquen al menos un par de transformaciones, además de que la mejora en el rendimiento suele ser notable, pero por ahora mejor sigue avanzando con el resto de la tarea 👍

Muy optimista pero no hay tiempo para esas cosas 😅

**Comment by FeBalla** [comment]
> > Te recomendaría seguir probando **más adelante**, porque igual evaluaremos que apliquen al menos un par de transformaciones, además de que la mejora en el rendimiento suele ser notable, pero por ahora mejor sigue avanzando con el resto de la tarea 👍
> 
> Muy optimista pero no hay tiempo para esas cosas 😅

Cualquier actividad nueva puedes reabrir la _issue_
