### ISSUE TITLE
[Tarea 4] Rotacion en ImageDataGenerator

### ISSUE THREAD

**Issue by sopadeoliva** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#178]
Hola! Tengo una duda con las transformaciones de ImageDataGenerator. Al usar la rotacion, a veces esto le pasa a la imagen: aparecen lineas diagonales en las esquinas de la celula. No pasa siempre, pero lo suficiente como para que se note y pero me parecio raro. Alguien sabe por que o como hacer que no suceda?
Gracias!
<img width="258" alt="Captura de Pantalla 2021-12-05 a la(s) 19 53 11" src="https://user-images.githubusercontent.com/42161679/144767139-cdd3142d-c209-41a8-8a75-1111b45c2a65.png">
<img width="261" alt="Captura de Pantalla 2021-12-05 a la(s) 19 53 06" src="https://user-images.githubusercontent.com/42161679/144767137-e020fb5e-3a24-4913-a779-0eba8d300501.png">

**Comment by FeBalla** [comment]
Eso es un _bug_/_feature_ asociado a que cuando `ImageDataGenerator` rota, te quiere seguir manteniendo la relación de aspecto 1:1 y te rellena con lo que cree que va, donde a veces pasan cosas como esta. De todos modos, el _trade off_ te sigue saliendo a cuenta, puesto que tu modelo aprende más de lo que podría llegar a causar ruido.

Nosotros tuvimos también estos casos y sin batallar mucho llegamos a un 95% de _accuracy_ así que les debería funcionar sin ningún problema  para alcanzar el 80% solicitado😄
