### ISSUE TITLE
[Tarea 4] Actividad 2 Parte 2

### ISSUE THREAD

**Issue by mscuturrufo** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#179]
Hola! El código de RL hay que implementarlo también en el notebook o este puede mantenerse en el archivo .py??

**Comment by vicentevegaulloa** [comment]
Hola @mscuturrufo!

La parte 2 debe hacerse en un `.py`. De hecho, la idea es que sobreescriban en `snake_aleatoria.py` (por eso dejamos los comentarios indicando donde hacer cada actividad). También podrían copiar el archivo `snake_aleatoria.py` y trabajar sobre la copia de ese archivo si quieren tenerlo de referencia. 

Espero que haya quedado claro 😃 Éxito en tu tarea!
