### ISSUE TITLE
[Tarea 1] Implementación de A*

### ISSUE THREAD

**Issue by domingo2000** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#18]
Hola, tengo una duda, cuando implementamos nuestras heurísticas y corremos el main, está corriendo realmente A*, o tenemos que implementarlo para que funcione?, pregunto pues ya implemente la distancia de manhattan en el sokoban pero me está expandiendo casi los mismos nodos que BFS.

**Comment by Dietr1ch** [comment]
La implementación de A* es otra parte de la tarea. En el template A* es simplemente una copia de Dijkstra para que sus cambios sean pocos y todas las tareas queden con la misma estructura.

Por cierto, antes de implementar A* lean el código de `Greedy` para saber cómo usar la heurística.
