### ISSUE TITLE
[Tarea 4] Actividad 2 HAPPENED

### ISSUE THREAD

**Issue by Coolgatty** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#180]
Que significa cuando dice HAPPENED cuando entreno?

**Comment by FeBalla** [comment]
Podrías compartir una foto del error? No había escuchado antes de este 😮

**Comment by Coolgatty** [comment]
> 

`if self.is_collision() or self.frame_iteration > 100*(len(self.snake)):
            game_over = True
            reward = -10
            if self.frame_iteration > 100*(len(self.snake)):
                print("HAPPENED")
            return reward, game_over, self.score`

Sale de este pedazo de codigo en game.py pero ni idea como interpretarlo

**Comment by Coolgatty** [comment]
> Podrías compartir una foto del error? No había escuchado antes de este open_mouth

```
if self.is_collision() or self.frame_iteration > 100*(len(self.snake)):
            game_over = True
            reward = -10
            if self.frame_iteration > 100*(len(self.snake)):
                print("HAPPENED")
            return reward, game_over, self.score

```
Sale de este pedazo de codigo en game.py pero ni idea como interpretarlo

**Comment by vicentevegaulloa** [comment]
Hola @Coolgatty! 

"HAPPENED" es un print que hice cuando estaba probando el entorno para crear la tarea. Podrías ignorarlo y no pasa nada. Lo creé para saber cuando es que el juego se acaba por haber alcanzado el límite de pasos sin comer una comida. Realmente no afecta en nada y fue un error mía haberlo dejado. Puedes comentarlo si quieres pero no te preocupes por eso.

Éxito en tu tarea! 😄
