### ISSUE TITLE
[TAREA 4] Gráficos parte 1 , act 5 y 6

### ISSUE THREAD

**Issue by Mjtala** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#181]
Hola!
Se puede subir un screenshot de tensorflow mostrando el gráfico?

**Comment by FeBalla** [comment]
No, la idea es que ocupen el `history` al hacer `fit`. De todos modos, es muy sencillo, unas 3-4 líneas de código para que quede bonito y aparecen en la primera googleada :)
