### ISSUE TITLE
[Tarea 4] Recompensas por diferentes eventos

### ISSUE THREAD

**Issue by domingo2000** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#182]
Hola, quería saber si podemos cambiar los valores de la recompensa para algunos eventos, pues me pasa que con las recompensas actuales se le premia también por "no morir" por lo que me gustría poder cambiar dicha recompensa a 0 si fuera posible para que el agente no vea dicho evento como algo bueno ni malo.

**Comment by domingo2000** [comment]
Edito, me di cuenta que era -= en el reward de moverse, no  += asi que no lo cambiaré por ahora, igual no se si las rewards se pueden cambiar como parámetros del problema o no

**Comment by vicentevegaulloa** [comment]
Hola @domingo2000! 

No pueden cambiar los rewards. Si quieren, podrían cambiarlos para ver que pasa y entender mejor el ambiente, pero su agente debe ser entrenado con las recompensas definidas en `game.py`. El hecho de que la serpiente reciba una recompensa negativa por dar un paso tiene una finalidad, y entender esa finalidad te ayudará a responder la última pregunta de la actividad 3.

Cualquier duda estaré atento a los comentarios. Éxito en tu tarea! 😄
