### ISSUE TITLE
[Tarea 4] States de Snake

### ISSUE THREAD

**Issue by acastill20** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#183]
Hola, quería saber si es necesario utilizar toda la información que nos otorga la función get_state para definir el espacio de estados en la q-table. A esto me refiero que considero que algunas de los datos que obtengo no son realmente necesarios para mi estado, reduciendo por ejemplo, si quitara un punto de información, mi espacio de 2^11 a 2^10.

**Comment by vicentevegaulloa** [comment]
Hola @acastill20!

Tu análisis es super interesante. Sin embargo, no puedes ignorar elementos del estado que te entrega `get_state()` ya que todos son necesarios para conocer el estado del agente.  Efectivamente se puede reducir la cantidad de estados, pero considerando el valor de todos los elementos. Te sugiero seguir pensando en como reducir la cantidad de estados de la Q-Table pero mirando los elementos de cada estado como un conjunto más que individualmente.  Espero que te sirva!

Éxito en tu tarea! 🚀
