### ISSUE TITLE
[Tarea 4] [Parte 2.2] helper.py no muestra nada :(

### ISSUE THREAD

**Issue by sopadeoliva** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#184]
Holi, estoy en la parte de aplicar Q-learning y queria usar el helper.py, pero no me aparece nada cuando lo corro con la terminal. Solo se ejecuta y termina como en aprox 1s.
Consejos?

**Comment by vicentevegaulloa** [comment]
Hola @sopadeoliva!

El archivo `helper.py` no se debe correr por si solo. Es un modulo que se importa en el archivo de tu snake y que llamas con la función `plot()`. Un ejemplo de esto se puede ver en `snake_aleatoria.py`, donde al final del archivo se llama a `plot()`. Si descomentas la linea en donde se llama, podrás visualizar los scores del snake.

Espero que haya quedado claro. Cualquier cosa estaré atento a los comentarios 😄 Éxito en tu tarea! 🚀
