### ISSUE TITLE
[Tarea 4, Parte 2 Bonus] Medición de rendimiento

### ISSUE THREAD

**Issue by sopadeoliva** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#186]
Hola! Quería saber cómo se iba a medir el rendimiento de esta parte. Asumo hasta ahora que se podría usar el promedio de los scores de varios juegos, o quizá un record? Pregunto por curiosidad no más :)

**Comment by vicentevegaulloa** [comment]
Hola @sopadeoliva!

El rendimiento de la snake se medirá con el score promedio de n partidas. Puedes tomar 100 como referencia si quieres practicar y medirlo tu. 

Éxito en tu tarea! 🐍
