### ISSUE TITLE
Duda Implementación Actividad 2

### ISSUE THREAD

**Issue by DomingoCarvajal** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#187]
Hola! Tenía 2 dudas con respecto a la implementación de la función.

1. Que se hace si el valor que da al multiplicar el kernel por la submatriz da menor a 0 o mayor a 255? Para mi lo mas natural es que hay que dejar el pixel en 0 y 255 en cada caso.

2. Tenemos que estandarizar la imagen? Para que se hace esto?

Pregunto por que los resultados de las convoluciones son muy diferentes dependiendo de que se decida hacer en ambas situaciones.

**Comment by FeBalla** [comment]
Hola!
Buena pregunta. En estricto rigor, si estuviéramos trabajando en más bajo nivel, se debería manejar esos casos. Sin embargo, matplotlib y su `plt.imshow` ya los maneja, por lo que no resulta estrictamente necesario tenerlo en cuenta, ya que la librería trunca los valores.

De todos modos, una buena alternativa (que es la que les recomendamos) es estandarizar la imagen. De hecho, para procesar los datos en la red neuronal **DEBEN ESTANDARIZARLOS**. La teoría detrás de porque esto es mejor es un poco compleja de explicar, pero en palabras sencillas se obtienen mejores resultados, con menos ruido, utilizando inputs entre 0 y 1.
