### ISSUE TITLE
Uso de función evaluate

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#188]
Hola, se puede usar model.evaluate(X_test, y_test) para medir el accuracy? Cual sería la diferencia con predict y luego usar accuracy_score?

**Comment by FeBalla** [comment]
Sí se puede usar `evaluate`. El problema de `accuracy_score` es que hace la comparación exacta y recuerden que ustedes están usando una función de activación sigmoide que les da la probabilidad de pertenecer a una clase.
