### ISSUE TITLE
Actividad 1.2 tamano imagenes

### ISSUE THREAD

**Issue by mmontecino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#189]
Probando me di cuenta que si uno achica los tamanos de las imagenes, las siluetas aparecen mas marcadas luego de aplicar la funcion, podemos aplicar ese cambio y cambiar su tamano por ejemplo a 250x250 o las trabajamos con el tamano original?

**Comment by FeBalla** [comment]
Las transformaciones de tamaño quedan totalmente a criterio suyo, siempre y cuando expliquen el motivo :)
