### ISSUE TITLE
[Tarea 1] Implementación IDDFS

### ISSUE THREAD

**Issue by matumartinez** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#19]
Hola!

Para esta parte de la tarea no entiendo en qué parte se debe implementar el algoritmo. Además, me gustaría saber dónde se puede ver la implementación de los que ya están hechos. En la carpeta "algorithms" están las clases para cada uno, pero por ejemplo la de BFS y la de DFS son casi iguales. Donde se encuentra la implementación de la búsqueda con BFS y DFS?

**Comment by Dietr1ch** [comment]
Hola,

Efectivamente BFS y DFS son casi iguales. Sus implementaciones están completas!

Sabemos que lo único distinto que hacen es elegir Nodos de open de forma distinta, y en la
implementación resulta dentro de Open usan la lista como stack o como queue, así no pueden
ser muy distintos.

También, ambos tienen un set pequeño, pero ilustrativo de tests, en los que puedes apreciar
el órden de expansión que usan.


Para la implementación de IDDFS, hay un [archivo listo](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/tree/assignment/search/algorithms/iddfs.py), pero no implementa nada útil todavía. En vez de buscar
simplemente dice que no hay soluciones (El `return None` incondicional).
