### ISSUE TITLE
Tarea 4 bonus 2

### ISSUE THREAD

**Issue by sebastianbreguel** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#190]
Hola! Tenía una duda respecto al archivo csv que hay que entregar en caso de querer postular al bonus. Si yo modifique los estados a 8 posibles, no 11, cómo debo entregar el archivo csv? en el formato de estados que trato yo mi modelo o debo "devolverlo" a 11 estados para lograr entregar la q-table tal como sale en el enunciado?
Gracias!

**Comment by vicentevegaulloa** [comment]
Hola @sebastianbreguel!

Los 11 son elementos de los estados, no estados, y debía trabajarse con todos ellos. De todas formas, si lo hiciste así y te funcionó deberías "devolverlo"  a una q-table de 11 estados en el formato que se especifica en el enunciado. Esto **debe ser al pie de la letra** porque de otra forma no se podrán evaluar bien tus resultados en el bonus.

Éxito! 🚀
