### ISSUE TITLE
Ayudantia 1

### ISSUE THREAD

**Issue by Huasito-Appel** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#2]
Ya esta subido el Notebook y el ppt, los que no fueron recomiendo ver el video antes que el ppt para que no se confundan en el ejemplo de A*, intentare subirles una capsula hoy con lo mismo mejor explicado.
Estos son los links de las paginas donde pueden jugar un poco con los algoritmos de Pathfinding.
 - https://clementmihailescu.github.io/Pathfinding-Visualizer/#   
 - https://qiao.github.io/PathFinding.js/visual/  
 Eso, nos vemos el prox viernes, exito en el control 😄

**Comment by cncosta** [comment]
Hola, el video link de los videos de la ayudantía no funciona, ¿dónde las están subiendo?

**Comment by Huasito-Appel** [comment]
Parece que hubo un problema con la nube de zoom, lo estamos subiendo a YouTube también, apenas este dejo el link acá.

**Comment by FeBalla** [comment]
> Hola, el link de los videos de la ayudantía no funciona, ¿dónde las están subiendo?

Ya están el link de la Ayudantía 01, ahí se irán subiendo las de todo el semestre!

**Comment by cncosta** [comment]
@FeBalla  Gracias!
