### ISSUE TITLE
[tarea 1] Test para la funcion SokobanSimpleManhattanDistance siempre pasan

### ISSUE THREAD

**Issue by crvargasu** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#20]
Hola, tengo una duda dado que al hacer la implementación simple de las distancias manhattan en sokoban, me di cuenta que los test siempre pasaban en el caso de que haya cajas. Es decir, que si uno cubre el caso para que de 0 en el caso de que no hay cajas, siempre se van a pasar los test. Es un error?

**Comment by Dietr1ch** [comment]
Ese test debería tener checkear por valores más altos, pero como también depende de la
heurística que ustedes proponen no podíamos elegir los valores :/

https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/problems/grid/sokoban_test.py#L188-L199
