### ISSUE TITLE
Windows: Error al ejecutar main.py en Windows. El sistema no puede encontrar la ruta especificada (/usr/bin/env).

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#21]
Al correr el código principal, sin hacer ninguna modificación me aparece el siguiente _output_ : "El sistema no puede encontrar la ruta especificada"

**Comment by VicenteMerino** [comment]
puede ser que estes tratando de correr el programa con la terminal en otro folder?

**Comment by ignacioarteaga99** [comment]
Esto aparece en la terminal:
/usr/bin/env python "g:\Mi unidad\8 SEMESTRE 4 AÑO\Inteligencia Artificial\GitHub\tarea-1-2021-2-ignacioarteaga99\main.py"

No creo que sea lo que dices ya que hice _click_ derecho en la carpeta donde estaba el _main_ y desde ahí abrí el VSCode

**Comment by Dietr1ch** [comment]
Puedes probar correr `python.exe main.py`?

El script dice que se tiene que correr con `/env/usr/env python`, y en windows al parecer no intentan emular `env`

**Comment by ignacioarteaga99** [comment]
Probé con **python.exe main.py** en la cmd y empieza a funcionar!
El tema es que no sé como hacer que funcione en el VSCode.

**Comment by Dietr1ch** [comment]
Buena!

Hmm, ni idea de VSCode, te puedo sugerir cambiarte a emacs? :P

Ahora, en serio, voy a probarlo en windows, pero me voy a demorar un poco más pq mi partición de windows sólo tiene steam instalado.

Mientras tanto, si alguien sabe se agradece la respuesta.

**Comment by Dietr1ch** [comment]
Acabo de probar en VSCodium en Win10.

  * Tenía `git` instalado con los overrides opcionales del `$PATH`, creo que lo único que me da es que pude usar bash en vez de la basura de shell que usa Windows.
  * Tenía VSCodium instalado, con un par de extensiones para otros lenguajes.
     - Instalé la extensión de Python más popular
  * No tenía Python, así que instalé anaconda y tambié le puse que modificara el `$PATH`.
  * Reinicié Windows, pq el `$PATH` al parecer no se actualiza en vivo.
  * Instalé un par de paquetes con `conda`,
    - `conda install pytest` (ya estaba instalado
    - `conda install termcolor` es el único paquete que faltaba. Conda viene con numpy, pero quizás otras distribuciones de python no lo traigan.
  * Abrí la terminal dentro de VSCodium luego de clonar y abrir el repo
    - Fui a la raíz del repo y simplemente corrí `pytest`.

![vscodium-pytest](https://user-images.githubusercontent.com/2096594/133550165-fab76bb8-68db-40e8-a6ee-ed7a8f75ad29.png)

**Comment by ignacioarteaga99** [comment]
Gracias profe! Cuando lo corro en la terminal no hay problema, sin embargo, al correr el programa main.py en si me tira el siguiente error:

Solving this Grid2D problem with the '<class 'search.problems.grid.board2d.Grid2DManhattanDistance'>' heuristic,
Traceback (most recent call last):
  File "g:\Mi unidad\8 SEMESTRE 4 A�O\Inteligencia Artificial\GitHub\tarea-1-2021-2-ignacioarteaga99\main.py", line 315, in <module>
    main()
  File "g:\Mi unidad\8 SEMESTRE 4 A�O\Inteligencia Artificial\GitHub\tarea-1-2021-2-ignacioarteaga99\main.py", line 311, in main
    compare(algorithms, problem, heuristic_class)
  File "g:\Mi unidad\8 SEMESTRE 4 A�O\Inteligencia Artificial\GitHub\tarea-1-2021-2-ignacioarteaga99\main.py", line 84, in compare
    print(problem.start_to_str())
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 13-19: character maps to <undefined>

Me pregunto si está bien con que únicamente corra en la terminal y desde ahí trabajo o si tiene que ser en el código mismo, porque la verdad me es súper molesto que me tire error al ejecutar el main, ya que no sé si se está ejecutando como debería y como al resto de mis compañeros.

**Comment by ignacioarteaga99** [comment]
¿Qué debería ocurrir al yo correr el programa main.py desde el editor de códigos? Porque eso me da un punto de partida para saber si mi programa está bien y puedo o no comenzar a trabajar con él

**Comment by ignacioarteaga99** [comment]
¿Qué debería ocurrir al yo correr el programa main.py desde el editor de códigos? Porque eso me da un punto de partida para saber si mi programa está bien y puedo o no comenzar a trabajar con él

**Comment by Dietr1ch** [comment]
> Cuando lo corro en la terminal no hay problema.

Entonces funciona bien. `main.py` es un script de consola y asume soporte de unicode y colores.

>  sin embargo, al correr el programa main.py en si me tira el siguiente error,
> ```
> Solving this Grid2D problem with the '<class 'search.problems.grid.board2d.Grid2DManhattanDistance'>' heuristic,
> Traceback (most recent call last):
>   File "g:\Mi unidad\8 SEMESTRE 4 A�O\Inteligencia Artificial\GitHub\tarea-1-2021-2-ignacioarteaga99\main.py", line 315, in <module>
>     main()
>   File "g:\Mi unidad\8 SEMESTRE 4 A�O\Inteligencia Artificial\GitHub\tarea-1-2021-2-ignacioarteaga99\main.py", line 311, in main
>     compare(algorithms, problem, heuristic_class)
>   File "g:\Mi unidad\8 SEMESTRE 4 A�O\Inteligencia Artificial\GitHub\tarea-1-2021-2-ignacioarteaga99\main.py", line 84, in compare
>     print(problem.start_to_str())
>   File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
>     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
> UnicodeEncodeError: 'charmap' codec can't encode characters in position 13-19: character maps to <undefined>
> ```

Esto es un problema de encoding, y no sé dónde está corriendo.
Si es que esto abre el terminal ordinario de Windows, `cmd.exe`, definitivamente no va a funcionar.


> Me pregunto si está bien con que únicamente corra en la terminal y desde ahí trabajo o si tiene que ser en el código mismo, porque la verdad me es súper molesto que me tire error al ejecutar el main, ya que no sé si se está ejecutando como debería y como al resto de mis compañeros.

Te funciona en el terminal de VSCode, que es un terminal mejor que el que viene en Windows.
En general es súper molesto trabajar en Windows por problemas como estos, pero la verdad no entiendo cuál es el problema con simplemente usar el terminal de VSCode.

**Comment by ignacioarteaga99** [comment]
Estoy tratando de utilizar el terminal de VSCode y me tira ese error de _encoding_. Por favor ayuda que ya he perdido como 4 días en los que no he podido avanzar.

**Comment by Dietr1ch** [comment]
> Estoy tratando de utilizar el terminal de VSCode y me tira ese error de encoding. Por favor ayuda que ya he perdido como 4 días en los que no he podido avanzar.

:thinking: 

> Gracias profe! Cuando lo corro en la terminal no hay problema, sin embargo, al correr el programa main.py en si me tira el siguiente error:

O sea, `python main.py` desde cualquier terminal, `VSCode` o `cmd.exe`, te tira ese error de encoding?

Puedes probar con Python 3.8? Yo estaba usando la 3.8.8 según la screenshot y tu error dice que usas Python 3.7.

**Comment by vWing7** [comment]
Hola, yo descargué el codigo base y lo corrí con python 3.7.9 en VSCode, funciona bien, me podrías dar más info de tu setup?, podria ser que estes usando otra versión de python que tienes instalada?, o que estés corriendo con la extensión de WSL? Además cuando corres en vscode, en la esquina inferior izquierda, que version de python aparece? quizas un screenshot de vscode cuando corres puede servir también

**Comment by Dietr1ch** [comment]
BTW, el main también me funciona bien, desde ambos terminales.

Algo está roto con tu setup de Python. Puedes instalar Anaconda? 

![IMG_20210916_200549_976](https://user-images.githubusercontent.com/2096594/133717711-57afd51e-5bb2-4bb0-b167-54007b4d9467.png)

![IMG_20210916_201047_835](https://user-images.githubusercontent.com/2096594/133718165-5a4c726c-6ce9-42ea-8317-959d2c9d64f5.png)

**Comment by ignacioarteaga99** [comment]
Estoy intentando correrlo desde el VSCode, actualicé a la versión 3.9.7 de Python y aún así no funciona. 
![image](https://user-images.githubusercontent.com/48535635/133790295-f8cd8adb-5d64-4832-ba8f-6026b4da8c7b.png)

**Comment by Dietr1ch** [comment]
Y probaste instalando este paquete que dicen al buscar "Windows UnicodeEncodeError"?

https://stackoverflow.com/a/32176732

**Comment by FeBalla** [comment]
Como no hay nueva actividad, cerraré la _issue_ por ahora
