### ISSUE TITLE
[Tarea 1] Implementación IDDFS (Otra vez)

### ISSUE THREAD

**Issue by matumartinez** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#22]
Hola!

Sigo con dudas para esta parte de la tarea. En iddfs.py no hay elementos que posee dfs.py, como por ejemplo el Open(). Puedo agregarlo o no es la idea? No entiendo hasta qué punto puedo modificar iddfs.py sin romper la estructura del programa entero.

Saludos

**Comment by Dietr1ch** [comment]
Hola!

Para implementar IDDFS no deberían necesitar una Open ni Nodos a menos que re-implementen DFS con límites.
Les recomiendo simplemente extender DFS para soportar límites de profundidad y dejar que el límite default sea infinito, e
implementar `search` (bueno, realmente `_actually_search`).


Quizás la confusión realmente ocurre porque en el código `class SearchAlgorithm` mezcla la interfaz que queríamos,
que sólo necesita que se implemente `search` (y `_actually_search`), con la implementación abstracta de lo que debiese
ser `GenericSearchAlgorithm` que usan casi todos los algoritmos y  da una implementación de `search` (realmente `_actually_search`) a cambio de pedir una implementación de `reach`, Open y Nodos.

**Comment by VicenteMerino** [comment]
Ptofesor, y que pasa en el caso de que no haya solución? Al poner profundiad infinita, voy a seguir iterando hasta el infinito. No debería poner un limite enter? O esto solamente lo debo ver con el self.expansions_limit, aumentandolo de ser necesario? (ya que ahora hay muchas mas expansiones)

**Comment by Dietr1ch** [comment]
> y que pasa en el caso de que no haya solución? Al poner profundiad infinita, voy a seguir iterando hasta el infinito.
Bueno, si el espacio es finito, entonces cualquier algoritmo que sea correcto en grafos va a terminar eventualmente.

Ahora, si el espacio de estados es infinito, o en la práctica indistinguible de infinito (onda, ya es comparable con la cantidad de átomos en la superficie de la tierra), entonces claro, el programa no va a terminar, pero no deja de ser correcto.

Como no tenemos control del tamaño del espacio de estados, es que [imponemos un límite](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/algorithms/search.py#L239-L242) en cuántas expansiones estamos dispuestos a hacer antes de ya asumir que no queremos intentar terminar la ejecución de la búsqueda.

Ése límite de `search.py` va a tener que seguir siendo respetado. La implementación de DFS que deberían reusar ya soporta un el límite de expansiones, pero falta una manera de actualizarlo al crear una instancia de DFS en cada iteración de ID-DFS.

**Comment by robertov1** [comment]
> Les recomiendo simplemente extender DFS para soportar límites de profundidad y dejar que el límite default sea infinito

Hola profesor!

Con esto se refiere a que podemos modificar la implementación de DFS del código base para que soporte límites de profundidad?
