### ISSUE TITLE
[Tarea 1] Pequeña duda Sokoban: SimpleManhattanDistance ignora muros?

### ISSUE THREAD

**Issue by Zetaku1** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#23]
Hola,

La heurística de simple manhattan distance para Sokoban toma en cuenta los muros o los ignora?

Muchas gracias!

**Comment by FeBalla** [comment]
> Hola,
> 
> La heurística de simple manhattan distance para Sokoban toma en cuenta los muros o los ignora?
> 
> Muchas gracias!

Esto generalmente depende de la modelación de los muros, pues una celda puede tener un muro en alguna de sus aristas o directamente ser una celda-muro. En este caso, se está utilizando la segunda manera. Por otra parte, el no considerar los muros al calcular la distancia Manhattan no es tan trivial como puede parecer, aunque tampoco es tan complejo.

Ahora, respondiendo a tu pregunta, te diría que debes considerar los muros.

**Comment by domingo2000** [comment]
Pero si tomo la ausencia de muros como una relajación del problema no debería tener problemas con la heurística cierto? Podría dejarlo como distancia de manhattan simple y argumentar de dicha forma?

**Comment by Dietr1ch** [comment]
Realmente yo esperaría que ignorasen los muros, de otra forma su heurística se empieza a parecer mucho
a resolver el problema y puede que conlleve hacer más cálculos que buscar con una heurística más simple.

Además es bastante no trivial resolver la distancia considerando los muros, es otro problema de búsqueda
incluso aunque ignores que el agente tiene que poder mover las cajas.

**Comment by Dietr1ch** [comment]
> Pero si tomo la ausencia de muros como una relajación del problema no debería tener problemas con la heurística cierto?
Claro

> Podría dejarlo como distancia de manhattan simple y argumentar de dicha forma?

Si, lo importante es mostrar consistencia, ya que si no A* se puede portar muy mal.
