### ISSUE TITLE
Sokoban: Falta una función que utiliza la heurística de manhattan y contar acciones

### ISSUE THREAD

**Issue by Zetaku1** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#24]
Hola!

Viendo el [Listado](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/problems/grid/sokoban.py#L314-L320) de funciones heurísticas para Sokoban, me he dado cuenta de que falta agregar la función de heurística que cuenta la distancia manhattan y además las acciones necesarias del agente para acercarse a ellas.

Me pregunto si se va a definir un nombre tipo ```SokobanSimpleManhattanActionDistance``` para que al momento de corregir no tengan que ver el nombre que le puso cada alumno para testear o si es que esta implementación va en otro lado que no he visto.

**Comment by VicenteMerino** [comment]
Tengo la misma duda, yo la implementé en SokobanBetterDistance, pero igual vendría faltando una heurística.

**Comment by Dietr1ch** [comment]
Ohh, que buen detalle.

Sí, sería ideal que todos usaran el mismo nombre, me quedaría con el tuyo para evitar que hayan demasiadas alternativas.

**Comment by domingo2000** [comment]
aaa yo lo deje con la action distance metida en manhattan distance, asumiendo que me pondrán ambas heuristicas buenas (Dado que si logré hacer la de manhattan la del personaje es literal una linea extra 😄 )

**Comment by JuanpaBC** [comment]
Hola, solo para confirmar, tenemos que agregar la subclase de Heuristic "SokobanSimpleManhattanActionDistance" en sokoban.py en la lista que retorna el staticmethod all_heuristics de la clase SokobanProblem, y además definir esa subclase más abajo con las demás. Sería eso o me estaría faltando algo?

**Comment by JuanpaBC** [comment]
vale muchas gracias!

**Comment by Mjtala** [comment]
> Ohh, que buen detalle.
> 
> Sí, sería ideal que todos usaran el mismo nombre, me quedaría con el tuyo para evitar que hayan demasiadas alternativas.

SokobanSimpleManhattanActionDistance este????? o SokobanBetterDistance??

**Comment by robertov1** [comment]
Hola! 

Puede ser que al agregar la subclase SokobanSimpleManhattanActionDistance a all_heuristics, también se tengan que cambiar los últimos 3 test de Sokoban?

Especificamente en los assert habría que agregar "SokobanSimpleManhattanActionDistance": 0 ó "SokobanSimpleManhattanActionDistance": INFINITY, dependiendo del test

**Comment by Dietr1ch** [comment]
> Hola!
> 
> Puede ser que al agregar la subclase SokobanSimpleManhattanActionDistance a all_heuristics, también se tengan que cambiar los últimos 3 test de Sokoban?

Es así, ya que eso hace que el test pruebe más funciones.

**Comment by robertov1** [comment]
Perfecto, gracias!
