### ISSUE TITLE
[Tarea 1] Error ejecutando tests!

### ISSUE THREAD

**Issue by sebaew98** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#25]
Hola estoy tratando de probar los tests corriendolos y me tira el siguiente error.

Traceback (most recent call last):
  File "/Users/seba/Documents/IA/tarea-1-2021-2-sebaew98/search/algorithms/astar_test.py", line 9, in <module>
    from search.algorithms.astar import AStar
  File "/Users/seba/Documents/IA/tarea-1-2021-2-sebaew98/search/algorithms/search.py", line 14, in <module>
    from search.space import Heuristic, Space
ModuleNotFoundError: No module named 'search.space'; 'search' is not a package

**Comment by Dietr1ch** [comment]
Hola,

Creo que falta información.

Si es que ejecutaste `python astar_test.py` entonces estás corriendo mal los tests.
Creo que es el caso porque los módulos se definen desde la raíz del proyecto y si abres python desde un sub-directorio
no se va a encontrar el árbol correcto de módulos.

La forma de correrlos, es desde la raíz del proyecto ejecutar `pytest`.

**Comment by sebaew98** [comment]
osea que se corren todos los test juntos? no se pueden correr por separado?

**Comment by Dietr1ch** [comment]
Por default si. Obvio, puedes elegir un archivo en particular y también tests específicos dentro de un archivo.

Lée el manual de pytest, o al menos `pytest --help`
