### ISSUE TITLE
[Tarea 1] Tests a implementar

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#26]
Hola, una pregunta. Para la tarea solo debo implementar los tests skippeados, sin preocuparme por el coverage? O adicional a eso debo implementar tests hasta que el coverage sea de un 100%?

**Comment by Dietr1ch** [comment]
Hola,

IMHO 100% coverage nunca debiese ser un objetivo en si mismo, 

> When a measure becomes a target, it ceases to be a good measure.  -- Marilyn Strathern


Los tests skippeados son un mínimo, y dependiendo de lo que estén implementado puede que les
convenga crear un par de tests extra para evitar tener que debuggear algún caso-borde complicado.

Ahora, qué tests agregar? Depende un poco de lo que estés arreglando, en general quieres desde
el test poder verificar que tus funciones son correctas (bueno, que no son incorrectas ;P).

Por ejemplo, en las heurísticas, los tests revisan el valor de la heurística en puzzles en donde se puede
calcular a mano, y que ojalá consideren casos de borde probables para la implementación.
Muchas veces es mejor escribir varios tests simples en vez de tratar de hacer uno que revise todo, ya
que quieres que al romperse un test sea obvio dónde es que hay algo mal implementado.
