### ISSUE TITLE
Problemas implementando IDDFS.

### ISSUE THREAD

**Issue by crvargasu** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#27]
Hola,

He estado con un error muy extraño, que luego de muchas horas debuggear, me di cuenta que se produce cuando no retorno luego de una iteración.

Estoy implementando la funcion de la siguiente forma

![Screenshot from 2021-09-15 22-49-25](https://user-images.githubusercontent.com/48322767/133536241-688cdbf9-4e7f-4a34-96ee-d8946c5b88fb.png)

De manera de que en el  `while True` recibo los valores que me da la funcion principal. El error es producido cuando no retorno el valor de la variable `sol`, es decir, se hace una iteración y la funcion principal devuelve `sol = None`, debo retornar ese valor en el while de la forma:

```
if sol == None:
      return None
```

En caso contrario, se cae.

**Comment by Dietr1ch** [comment]
Hola,

La verdad no entiendo muy bien tu problema.
Lo que parsié me dice si no retornas `sol` en la primera y única iteración de ese `while True` algo "se cae", pero no
debiese ser el caso.

A qué te refieres con que se cae? Se cae porque en la 2da iteración la llamada a `generic_search` no termina, o luego
de ocupar muchos recursos el kernel termina matando a tu proceso?
Y por qué se cae? "se cae" es pésima descripción de tu problema ya que no me da mucha información para ayudarte.

**Comment by crvargasu** [comment]
Para dar un poco más de contexto, el mi `generic_search` funciona como el de clases, es decir

```
def generic_search(g: Graph, starting_node, goal_function, limit) -> Solution:
    Closed = set()  # Closed: Explored nodes (We only store the state)
    Open = MagicalCollection()  # Open: Known, but still unexplored Nodes
    Open.add(starting_node)

    while Open:
        node = Open.pop()  # Takes a node from Open. Which one?
        if node.cost > limit:
            continue
        if is_goal(node):
            return path(node)
        Closed.add(node)
        for n in node.neighbors():  # Creates Nodes around node.state
            if n.state in Closed:
                continue
             Open.upsert(n)  # Insert|Update to keep Nodes a Spanning Tree (if needed)

    return None
```

Donde voy sacando los nodos que cumplen con la profundidad delimitada, hasta que ya no me quedan más. En ese caso, se retorna None de la función y pasa a `generic_search_sketch`, donde hago el manejo de la MagicalCollection y esas cosas. El tema, es que cuando paso a dicha función, en el caso que el valor retornado sea `None` (lo cual se da cuando aún no encuentro la solución en esa profundidad), debo retornar ese valor, en caso contrario, el programa me tira un error de que el `state` que se quiere remover del set no está, lo cual me parece muy extraño, dado que no tiene nada que ver con si está o no el retorno del `None`. Puede ser que main corta el algoritmo al recibir cierta cantidad de retornos None?

**Comment by Dietr1ch** [comment]
Oh, no estás compartiendo estado (as-in estado del programa, no confundir con estados del problema de búsqueda) entre las distintas búsquedas de DFS?

Me parece que el problema es que tu DFS con profundidad 2 no corre de forma limpia y ve  cosas extrañas de lo que quedó al correr DFS con profundidad 1 antes.

**Comment by crvargasu** [comment]
Si, pense en eso, pero le aplico la restricción de que se pase al siguiente limite solo cuando ya no quedan nodos en la open de la profundidad actual para buscar. Luego de eso, pueblo la open con los hijos de los últimos nodos. Algo que quizás aporte información, es que con un límite de profundidad de 2 y sumando 1 al alcanzar la profundidad, se alcanzan a hacer 14 expansiones, es decir, se alcanzan a hacer un par de repoblamientos a la open, dado que se alcanza a cambiar de profundidad varias veces

**Comment by Dietr1ch** [comment]
El problema es que lo que quieres implementar, en caso de quedar bien y optimizarse un poco va a ser simplemente DFS con un par de pausas entre medio.

ID-DFS realmente corre DFS desde 0 varias veces con límites incrementales.
No se comparte estado más allá del límite usado en DFS. Tratar de compartir nodos de Open entre distintos runs de DFS te lleva a algo totalmente distinto.

**Comment by Dietr1ch** [comment]
BTW, para ayudar a confirmar lo "ineficiente" que es IDFS acá hay una visualización bastante buena. (lo que no me gustó es que el grafo de estados es un árbol y es menos general de lo que hace nuestro DFS que si tiene un Closed Set).

https://youtu.be/7DLmUKHdi6A?t=54
