### ISSUE TITLE
[Tarea 1] Complejidad heurística mejorada

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#28]
Hola, debo procuparme por la complejidad de mi heurística mejorada? O  solo que de un mejor camino? Ademas cuando dice que muestre un estado donde se vea que este esta heuristica es mejor, como se evalua eso? Mmostrando que el camino es mas corto?

**Comment by Dietr1ch** [comment]
Hola!

> debo procuparme por la complejidad de mi heurística mejorada?

No, pero sería interesante tener un análisis pequeño de si vale la pena o no calcular una heurística mucho más precisa en este puzzle.

>  O solo que de un mejor camino? 

Notar que si la heurística es consistente, como debiese ser, vas a encontrar un camino óptimo también, podría diferir un poco en caso de que hayan soluciones múltiples.

Cuando ya tienes 2 heurísticas consistentes a comparar, hay 2 formas de medir que una heurística es más informativa (mejor).
  1. Mostrar que en algún estado en particular la heurística se acerca más a $h^*$.
  2. Mostrar evidencia estadística que A* tiende a expandir menos nodos al correr con la heurística mejor.
  
 
 En la respuesta se espera que simplemente den un estado que permita distinguir a su heurística de las que vimos
 en el curso (1), pero la segunda opción también es válida y les debiese permitir encontrar evidencia de un estado
 para 1 una vez que encuentren en qué expansiones A* empieza a expandir otros nodos.
