### ISSUE TITLE
ID-DFS: Error en costo óptimo en test de grilla

### ISSUE THREAD

**Issue by domingo2000** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#29]
Hola, estaba implementando idfs y vi que [sale que la solución optima de un test de de 17](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/algorithms/iddfs_test.py#L67), haciendolo a mano me doy cuenta que la mejor solución es en 19 movimientos, por lo que cambiaré el test, pero es para notificar el bug :)

**Comment by Dietr1ch** [comment]
Hmm, nada que decir, gracias por reportarlo.

Math is hard I guess (?).

**Comment by JuanpaBC** [comment]
muchas gracias, ahí pillé el 17 y lo cambié a 19!

**Comment by mpenalozag** [comment]
La solución óptima de este creo que esta bien en 17. También chequee a mano

**Comment by jiaranda** [comment]
entonces esto es 19 o 17? a mi también me da 19 el código :thinking:

**Comment by Dietr1ch** [comment]
:thinking: 

Bueno, la verdad no hice el ejercicio de contar y supuse que podría haber hecho un cambio después de borrar la solución, pero efectivamente tiene costo óptimo 17,

Acá está el último dígito del costo a cada casilla,
```
            "34567",
            "2####",
            "10987",
            "####6",
            "12345",
            "01234",
```

**Comment by robertov1** [comment]
Hola! 

Alfinal hay que cambiar algo en este caso?

También me da 19

**Comment by Dietr1ch** [comment]
Bueno, si cuentan o corren BFS se darán cuenta de que la solución óptima es de 17.

#67 habla de la sub-optimalidad de ID-DFS usando una implementación inadecuada de límite de profundidad.
