### ISSUE TITLE
[Tarea 1] Test idfs 2 expansion de nodos

### ISSUE THREAD

**Issue by domingo2000** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#30]
Me surgue la duda de porque pide el test que se expanda todo el arbol de búsqueda si podría irse por una rama y que pille la solución en solo 19 expansiones y no 21, adjunto imagen del test para que entiendan a cual me refiero, en la linea 70 está lo que no me hace sentido
![image](https://user-images.githubusercontent.com/40220174/133543615-8f1c018c-1741-4b98-98bb-ce5477041fe4.png)

([Código](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/algorithms/iddfs_test.py#L42-L72))

Edit: Toman las expansiones de idfs como todo lo que ha trabajdo, o solamente como la última expansion de dfs realizada?

**Comment by Dietr1ch** [comment]
Primero que nada. Está claro que la cantidad de expansiones no necesariamente va a ser 1:1 con la profundidad o no?

DFS podría explorar `URRDL` y encerrarse, teniendo que continuar por `URRDR`.
En general profundidad <= expansiones. Y esa es la profundidad que vas a ver en parte al mirar el largo de la solución que encuentre DFS.


---

Una vez que esté claro que las expansiones pueden ser más que el largo de las soluciones, miremos otra vez qué significa que ID-DFS haga X expansiones.

Yo considero que la línea 70 es demasiado conservadora.

Cuántos nodos expande DFS con profundidad 1? (digámosle DFS-1, pero en vd no tiene nombre :P) 3 nodos no?

Y DFS-2? 5 nodos o no?

Entonces cuántos expande ID-DFS para encontrar una solución a profundidad 17?

**Comment by Dietr1ch** [comment]
Ah, acabo de ver el edit.

> Toman las expansiones de idfs como todo lo que ha trabajdo, o solamente como la última expansion de dfs realizada?

Todas, estamos tratando de medir la cantidad de trabajo hecho, contando operaciones como proxy a contar CPU en un ambiente con muy poca varianza.
