### ISSUE TITLE
[Tarea 1] IDDFS restricciones para no volver a tomar el mismo camino

### ISSUE THREAD

**Issue by crvargasu** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#31]
Hola,

En [el ultimo test de IDDFS](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/algorithms/iddfs_test.py#L76-L94), me di cuenta que es un camino recto para ambos lados y debemos llegar con los movimientos justos, por lo que me surge la pregunta.

Debemos hacer una restricción para no devolvernos? esto es, dado que me di cuenta que en mi caso se suelen tomar caminos como 82->83 y un poco después, 83 -> 82 o cosas así.

Estoy un poco confundido, dado que arreglé el problema anterior de la issue que hice (efectivamente era [lo que me dijo](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Syllabus/issues/27#issuecomment-920553540)) y se supone que los DFS deben ser independientes, entonces no habría ninguna restricción que me impida devolverme?

**Comment by Dietr1ch** [comment]
Hola,

> Debemos hacer una restricción para no devolvernos?
> esto es, dado que me di cuenta que en mi caso se suelen tomar caminos como 82->83 y un poco después, 83 -> 82 o cosas así.

Nuestro DFS usa un Closed Set de todas maneras, así que no se debería devolver.

Lo que debieses ver (en un pasillo más corto) es algo así,

```
mapa:      g-----S------

IDFS(d=1): g----<S>-----   # Expandir con profundidad 1. Se expanden 3 nodos. Se descartan 2 de Open al final
IDFS(d=2): g---<<S>>----   # Expandir con profundidad 2. Se expanden 5 nodos. También se descartan 2 de Open al final
IDFS(d=3): g--<<<S>>>---
IDFS(d=4): g-<<<<S>>>>--
IDFS(d=5): g<<<<<S>>>>>-
IDFS(d=6): G<<<<<S>>>>>> # Se encuentra el objetivo 
```

Fíjate que la búsqueda siempre parte desde el estado inicial, creo que eso es lo que te confunde.

**Comment by crvargasu** [comment]
Respecto a esa pregunta, en el test sale 

`assert 2 * (length + 1) < iddfs.expansions`

No debería ser ?

`assert 2 * (length) + 1<= iddfs.expansions`

Dado que con un length de 100 se puede llegar en 201 movimientos

**Comment by Dietr1ch** [comment]
No, si el pasillo es de 100 de largo hacia ambos lados la última iteración de DFS va a expandir 100 nodos si tiene suerte, o ~201 si parte hacia el lado incorrecto primero.

Cuántos nodos se expanden en el ejemplo chico que di antes?

**Comment by crvargasu** [comment]
Pero en el test se esta pidiendo que sea `202<iddfs.expansions`

**Comment by crvargasu** [comment]
Además de que, si se expande hacia ambos lados 
```
mapa:      g-----S-------

IDFS(d=1): g----<S>------   # Expandir con profundidad 1. Se expanden 3 nodos. Se descartan 2 de Open al final
IDFS(d=2): g---<<S>>-----   # Expandir con profundidad 2. Se expanden 5 nodos. También se descartan 2 de Open
IDFS(d=3): g--<<<S>>>----   # ...
IDFS(d=4): g-<<<<S>>>>---
IDFS(d=5): g<<<<<S>>>>>--
IDFS(d=6): G<<<<<S>>>>>>-  # Se encuentra el objetivo 
```
Se demoraría el doble en del largo, es decir, para IDFS(d = 6) se demoraría `2 * (length)` (Si revisa el de la izquierda primero) o `2 * (length) + 1` (si revisa el de la derecha primero).

**Comment by crvargasu** [comment]
quizás el test debería ser así?

`assert iddfs.expansions <= 2 * (length) + 1`

**Comment by Dietr1ch** [comment]
Nuevamente, cuántos nodos se expanden en total en el ejemplo chico que di antes?

Al usar DFS con profundidad 1 se expanden 3, luego con profundidad 2, 5, y la búsqueda sigue hasta usar profundidad 6.


> Pero en el test se esta pidiendo que sea `202<iddfs.expansions`

Si, y eso es muy conservador.



> Si se expande hacia ambos lados
> 
> ```
> mapa:      g-----S-------
>
> > ``` 
> > IDFS(d=1): g----<S>------   # Expandir con profundidad 1. Se expanden 3 nodos. Se descartan 2 de Open al final
> > IDFS(d=2): g---<<S>>-----   # Expandir con profundidad 2. Se expanden 5 nodos. También se descartan 2 de Open
> > IDFS(d=3): g--<<<S>>>----   # ...
> > IDFS(d=4): g-<<<<S>>>>---
> > IDFS(d=5): g<<<<<S>>>>>--
> > IDFS(d=6): G<<<<<S>>>>>>-  # Se encuentra el objetivo 
> > ```
> 
> Se demoraría el doble en del largo, es decir, para IDFS(d = 6) se demoraría `2 * (length)` (Si revisa el de la izquierda primero) o `2 * (length) + 1` (si revisa el de la derecha primero).

No estamos tratando de que se demore menos, simplemente tratando de medir cuántas expansiones se harían.



> quizás el test debería ser así?
> 
> `assert iddfs.expansions <= 2 * (length) + 1`

No, sigues considerando sólo las expansiones del último DFS.

**Comment by crvargasu** [comment]
pero, el total de iteraciones de la profundidad máxima de IDFS toma en cuenta a todos los demás o no? Porque estamos tomando un estado ya encontrado y seguimos expandiendo desde ahí.

es decir, 
```
IDFS(d=5): g<<<<<S>>>>>--
IDFS(d=6): G<<<<<S>>>>>>- 
```
Se encontraría la solución en 12 - 13 iteraciones en ese mapa?

**Comment by crvargasu** [comment]
pero, el total de iteraciones de la profundidad máxima de IDFS toma en cuenta a todos los demás o no? Porque estamos tomando un estado ya encontrado y seguimos expandiendo desde ahí.

es decir, 
```
IDFS(d=5): g<<<<<S>>>>>--
IDFS(d=6): G<<<<<S>>>>>>- 
```
Se encontraría la solución en 12 - 13 iteraciones en ese mapa?

**Comment by Dietr1ch** [comment]
> pero, el total de iteraciones de la profundidad máxima de IDFS toma en cuenta a todos los demás o no? Porque estamos tomando un estado ya encontrado y seguimos expandiendo desde ahí.

ID-DFS hace 6 iteraciones, en cada una hace DFS con límites de profundidad distinto.
Cada DFS que hace expande varios estados, no te puedes olvidar de eso y quedarte sólo con lo que pasó en la última iteración de DFS.

> ```
> IDFS(d=5): g<<<<<S>>>>>--
> IDFS(d=6): G<<<<<S>>>>>>- 
> ```
> 
> Se encontraría la solución en 12 - 13 iteraciones en ese mapa?

No, si DFS parte hacia la izquierda, entonces vas a hacer 6 *expansiones* (El test de objetivo se hace antes de expandir, así que no se expande G).
De lo contrario, DFS expande todo el pasillo hacia la derecha, con 8 expansiones (hacia la derecha creo que hay un estado más), y después de expandir todos los estados de la derecha, empieza a expandir los de la izquierda para llegar a un total de 13 expansiones (sólo faltaría expandir el estado objetivo).

**Comment by crvargasu** [comment]
Ya creo que ahí nace la confusión. Yo entiendo expansion cómo buscar otro nodo (solo 1)

**Comment by crvargasu** [comment]
Ok creo que ahora entiendo mejor. Solo me queda una duda. De igual forma, el test pide una **expansión mayor a 202**, cuando se puede llegar con 201 iteraciones

**Comment by Dietr1ch** [comment]
> De igual forma, el test pide una expansión mayor a 202, cuando se puede llegar con 201 iteraciones

Por favor, puedes intentar ser más preciso? Si en vez de usar la terminología que está bien definida usas una propia sólo te haces más difícil entender las cosas y comunicar tus problemas.

Al contar iteraciones de sacar nodos de open en general vamos a hablar de expansiones, ya que a menos que encuentres el objetivo también vas a expandir un nodo, es decir, calcular los estados sucesores del estado al que representa ese nodo.


Ahora, en el ejemplo que di,

> mapa:      g-----S-------
> 
> IDFS(d=1): g----<S>------   # Expandir con profundidad 1. Se expanden 3 nodos. Se descartan 2 de Open al final
> IDFS(d=2): g---<<S>>-----   # Expandir con profundidad 2. Se expanden 5 nodos. También se descartan 2 de Open
> IDFS(d=3): g--<<<S>>>----   # ...
> IDFS(d=4): g-<<<<S>>>>---
> IDFS(d=5): g<<<<<S>>>>>--
> IDFS(d=6): G<<<<<S>>>>>>-  # Se encuentra el objetivo

Se corren 6 iteraciones de DFS cierto?
1. En la primera, se expanden `3` nodos, el nodo del estado initial, junto a sus sucesores directos. También se descartan 2 nodos de Open que quedan por sobre el límite (podrías nunca agregarlos a Open tb).
2. Al correr DFS con profundidad 2 se expanden `5` y se decartan 2.
3. Ahora, usando DFS con profundidad 3 se expanden `7` nodos. También se descartan 2 nodos.

Hasta el momento ya van 3+5+7 expansiones, y los siguientes usos de DFS harán cada vez más expansiones, ya que cada iteración que ID-DFS hace corriendo DFS con un límite mayor repite todo trabajo que la iteración anterior hizo.

**Comment by crvargasu** [comment]
Ya, si creo que es un error en el lenguaje, yo me refería siempre a que `expansion = iteración`, cuando no lo es. Lo que no me hace sentido, y por eso creo que nace la confusión es. Cual es la necesidad de que las iteraciones mayores vuelvan a buscar en los mismos nodos que ya buscamos? Todo el tiempo pensé que las iteraciones siguientes no buscan en los nodos que ya fueron buscados por anteriores iteraciones.

**Comment by Dietr1ch** [comment]
> Cuál es la necesidad de que las iteraciones mayores vuelvan a buscar en los mismos nodos que ya buscamos?

Se hace para evitar tener que usar tanta memoria, 
De hecho una implementación eficiente en tiene un solo estado en memoria en puzzles con acciones reversibles, y uno por cada nivel de profundidad en puzzles en que las acciones no son reversibles.
En clases mencionamos que este trade-off se paga en puzzles en que expandir Estados es muy rápido, tanto que es más rápido generarlos muchas veces a que pagar los costos de latencia al tener que ir al caché o la ram a buscar estados en Closed o en Open.
El puzzle de 15 es uno de estos casos, en el que sólo hay que manejar 16 chars (y 16 Bytes en lenguajes de bajo nivel) para mantener ese estado único.
Adora,la implementación simple de hacer para esta tarea está lejos de eso, ya que al reusar DFS para grafos vamos a seguir pagando el costo de manejar Open y Closed, pero la verdad es que usando Python tampoco teníamos esperanzas de llegar a algo demasiado eficiente.
Lo que buscamos en realidad es simplemente transformar a DFS en algo que de soluciones óptimas al construir ID-DFS sobre él. 

> Todo el tiempo pensé que las iteraciones siguientes no buscan en los nodos que ya fueron buscados por anteriores iteraciones.

Si, esto es pega extra que se repite, pero un trade-off que algunas veces se paga.

**Comment by Dietr1ch** [comment]
Ahh, y una cosa interesante.

Este truco de volver DFS iterativo se puede hacer también con A*, logrando ID-A*, o IDA*, pero no es trivial como en el caso de DFS.

El nuevo valor-f límite empieza a estar dado por el mejor valor-f que se descartó en la iteración anterior, pero ahora no se puede simplemente correr A*, ya que no quieres usar Open ni Closed.
Se sigue haciendo algo que explora en el órden de DFS, pero al evaluar el valor de los nodos usas su valor f. Esto hace algunas cosas un poco confusas, ya que sólo puedes terminar ese "DFS" si es que encuentras una solución que tiene como costo el límite de f o que resulta tener el mejor valor-f no explorado del "DFS" completo.
Esto puede hacer las cosas confusas y es la razón por la cual no lo mencioné en mayor detalle. Prefiero que entiendan A* bien a que lo terminen mezclando sin querer con detalles de ID-A*

https://en.wikipedia.org/wiki/Iterative_deepening_A*

**Comment by Zetaku1** [comment]
Hola!

Creo que no entiendo muy bien, al revisar los neighboring states al momento que dfs explora me doy cuenta que primero va full hacia la derecha y luego se devuelve. Eso en el caso de test_expansion_order. Hay que hacer de algún modo que recorra de la manera que se describe aca?

Siento que si limito el expansion limit de dfs simplemente lo que hace es:
```
G -----S>>>>--
```
en vez de 
```
G---<<S>>----
```

**Comment by Dietr1ch** [comment]
> Creo que no entiendo muy bien, al revisar los neighboring states al momento que dfs explora me doy cuenta que primero va full hacia la derecha y luego se devuelve.

Claro, DFS prefiere seguir el camino que ya tiene avanzado


> Siento que si limito el expansion limit de dfs simplemente lo que hace es:
> 
> ```
> G -----S>>>>--
> ```
> 
> en vez de
> 
> ```
> G---<<S>>----
> ```

No realmente, ojo que si bien puedes mantener un límite de expansiones a través de todas las iteraciones que corren un DFS, al hacer varios DFS con profundidad limitada lo que se ejecuta es lo siguiente,

ID-DFS(max_depth=1)
> ```
> G -----S------
> G -----S>-----
> G ----<S>-----
> ```

ID-DFS(max_depth=2)
> ```
> G -----S------
> G -----S>-----
> G -----S>>----
> G ----<S>>----
> G ---<<S>>----
> ```

ID-DFS(max_depth=3)
> ```
> G -----S------
> G -----S>-----
> G -----S>>----
> G -----S>>>---
> G ----<S>>>---
> G ---<<S>>>---
> G --<<<S>>>---
> ```

Y se sigue así hasta que se alcance a expandir el objetivo.

**Comment by Zetaku1** [comment]
Gracias! Se entiende

**Comment by VicenteMerino** [comment]
@Dietr1ch tengo una duda acá, haciendo unos cálculos rápidos, la cantidad de expansiones totales debería estar entre los 7000 y 20000. Mi programa imprime que son 10401. Mi punto, más allá del valor exacto es que si incorporamos el limite de expansiones como el definido (2500), entonces nunca vamos a alcanzar a encontrar la solución. El problema es que como tengo un límite de profundidad infinito si no uso un límite de expansiones, entonces mi primer test se va a quedar iterando por siempre, ya que la implementación vista en clases es ciega a cuando llego a la profundidad máxima del DFS original. Este ya fue un problema que mencioné en issues anteriores pero por más que la cabeceo no puedo solucionar este problema, o bien el test 1 se queda pegado (ya que itera infinito), o bien el test 3 me falla por el bajo límite de expansiones, ya que me mencionó que no debería modificar el límite de expansiones, sin embargo esta es la única solución que se me ocurre para calibrar entre ambas cosas. Si me podría guiar sería ideal.

PD: A lo que me refiero con que es ciega al limite real de DFS es que como tengo un while True incrementando el límite, entonces si ya no quedan estados por revisar, ya que se acabó el árbol de estados, entonces retornará None, como lo hace normalmente y volverá a entrar a la generic_search aunque no haya encontrado solución con el límite anterior

![image](https://user-images.githubusercontent.com/47841749/134612643-97d47de3-4a08-4b54-9cbf-18dc5111c61d.png)

**Comment by Dietr1ch** [comment]
> El problema es que como tengo un límite de profundidad *(máxima?)* infinito, si no uso un límite de expansiones, entonces mi primer test se va a quedar iterando por siempre.

Claro, la llamada a DFS con límite de profundidad debería también poder darte información a cerca de los nodos descartados, de modo que puedas saber que seguir incrementando el límite no va a descubrir resultados nuevos.

Exponer información adicional no es un problema difícil, SearchAlgorithm ya expone la cantidad de expansiones y otras estadísticas.
