### ISSUE TITLE
Objetivo sokoban

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#32]
Hola, tengo un par de dudas sobre sokoban:
- Si tengo más goals que boxes, hay solucion?
- Si tengo más boxes que goals, hay solucion?

No me queda claro cuál es el objetivo, que todas las boxes queden en algún objetivo, o que todos los goals tengan una box. Agradecería si me pudiesen explicar esto.

**Comment by Dietr1ch** [comment]
> Si tengo más goals que boxes, hay solucion?

Depende, pero lo esperable es que si

> Si tengo más boxes que goals, hay solucion?

No, la idea es que todas las cajas estén en un objetivo.
