### ISSUE TITLE
[Tarea 1]: Sokoban distancia a box

### ISSUE THREAD

**Issue by crvargasu** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#33]
Me surgió la duda, no está bien calcular la suma de la distancia a boxes por separado o no?

Teniendo el ejemplo: 
```
 "S                      B    B   G G"
```
En caso de sumar los boxes por separado no estaría tomando en cuenta que me puedo estar acercando a un Box mientras voy a otro o no?

**Comment by Dietr1ch** [comment]
> Me surgió la duda, no está bien calcular la suma de la distancia a boxes por separado o no?
> 
> Teniendo el ejemplo:
> 
> ```
>  "S                      B    B   G G"
> ```
>
> En caso de sumar los boxes por separado no estaría tomando en cuenta que me puedo estar acercando a un Box mientras voy a otro o no?

Claro, pero sólo estamos contando la distancia a LA caja más cercana.

En general las heurísticas sub-estiman $h^*$, ser muy preciso en las heurísticas tiene retornos negativos en términos
de cómputo, ya que calcular la heurística de cada estado se empieza a parecer mucho a resolver el problema original
y se calcula para muchos estados.

**Comment by crvargasu** [comment]
Hola, me surgió otra duda respecto a lo mismo, es válido usar la distancia a LA caja más lejana? Porque en ese caso sería una heurísitca aún mejor

**Comment by sofiaolmedos** [comment]
> Claro, pero sólo estamos contando la distancia a LA caja más cercana.
> 
> En general las heurísticas sub-estiman `h*`, ser muy preciso en las heurísticas tiene retornos negativos en términos
> de cómputo, ya que calcular la heurística de cada estado se empieza a parecer mucho a resolver el problema original
> y se calcula para muchos estados.

Hola! No entendí bien la respuesta. Si se da el caso de que más de una caja compartan el mismo objetivo más cercano, se puede considerar esa posición para ambas en la heurísitca? O se debe buscar otro goal para la otra caja?

**Comment by Dietr1ch** [comment]
> ¿Es válido usar la distancia a LA caja más lejana? Porque en ese caso sería una heurísitca aún mejor

Sería realmente mejor? :thinking: :thinking:


> > Claro, pero sólo estamos contando la distancia a LA caja más cercana.
> > En general las heurísticas sub-estiman `h*`, ser muy preciso en las heurísticas tiene retornos negativos en términos
> > de cómputo, ya que calcular la heurística de cada estado se empieza a parecer mucho a resolver el problema original
> > y se calcula para muchos estados.
> 
> Si se da el caso de que más de una caja compartan el mismo objetivo más cercano, se puede considerar esa posición para ambas en la heurística?

La última heurística propuesta no considera que es imposible poner 2 cajas en el mismo lugar, lo que sigue siendo una relajación del problema original.

**Comment by crvargasu** [comment]
> 
> Sería realmente mejor? :thinking: :thinking:
> 
> 


Bueno, el jugador tiene que llegar a las cajas, y sería mejor calcular la distancia a la caja más lejana que a la más cercana, dado que en el caso de la caja más lejana el valor de la heurística será mayor, por tanto más cerca del valor real de la heurística perfecta. No es así?

**Comment by BelenSilva1204** [comment]
> > ¿Es válido usar la distancia a LA caja más lejana? Porque en ese caso sería una heurísitca aún mejor
> 
> Sería realmente mejor? 🤔 🤔
> 
> > > Claro, pero sólo estamos contando la distancia a LA caja más cercana.
> > > En general las heurísticas sub-estiman `h*`, ser muy preciso en las heurísticas tiene retornos negativos en términos
> > > de cómputo, ya que calcular la heurística de cada estado se empieza a parecer mucho a resolver el problema original
> > > y se calcula para muchos estados.
> > 
> > 
> > Si se da el caso de que más de una caja compartan el mismo objetivo más cercano, se puede considerar esa posición para ambas en la heurística?
> 
> La última heurística propuesta no considera que es imposible poner 2 cajas en el mismo lugar, lo que sigue siendo una relajación del problema original.

Con este último comentario se refiere a que en la última heurística que debemos implementar no podemos considerar que cada caja tenga su goal propio?

**Comment by Dietr1ch** [comment]
> > > ¿Es válido usar la distancia a LA caja más lejana? Porque en ese caso sería una heurísitca aún mejor
> > 
> > 
> > Sería realmente mejor? thinking thinking
> > > > Claro, pero sólo estamos contando la distancia a LA caja más cercana.
> > > > En general las heurísticas sub-estiman `h*`, ser muy preciso en las heurísticas tiene retornos negativos en términos
> > > > de cómputo, ya que calcular la heurística de cada estado se empieza a parecer mucho a resolver el problema original
> > > > y se calcula para muchos estados.
> > > 
> > > 
> > > Si se da el caso de que más de una caja compartan el mismo objetivo más cercano, se puede considerar esa posición para ambas en la heurística?
> > 
> > 
> > La última heurística propuesta no considera que es imposible poner 2 cajas en el mismo lugar, lo que sigue siendo una relajación del problema original.
> 
> Con este último comentario se refiere a que en la última heurística que debemos implementar no podemos considerar que cada caja tenga su goal propio?

No, sólo muestra una manera en la que las heurísticas propuestas se equivocan al aproximar el costo faltante, y por lo tanto son una de las cosas que se podrían mejorar.
