### ISSUE TITLE
ID-DFS: Estadísticas acerca de los estados generados y alcanzados

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#34]
Hola, no tengo muy claro que quieren decir estas dos estadísticas. Cada vez que empiezo de nuevo en IDDFS deberían volver a setearse en 0?

**Comment by VicenteMerino** [comment]
Lo mismo con nodes_created, debería contarse desde 0 o contar el total?

**Comment by Dietr1ch** [comment]
Hola,

> no tengo muy claro que quieren decir estas dos estadísticas. Cada vez que empiezo de nuevo en IDDFS deberían volver a setearse en 0?

Claro que no deberían resetearse, sería trampa resetearlos al tener que volver a hacer DFS con una profundidad mayor.


Ahora, cra el significado de las estadísticas,
  * `states_generated`; Cantidad de estados generados. Cada vez que se expande un estado, se generan N estados sucesores, y el generar esos estados es en general costoso, por lo que es interesante saber cuánto trabajo se hizo en esa parte.
  * `states_reached`: Cuántas veces llegamos por un camino nuevo a un estado, esto ocurre al llegar a un estado por primera vez, o al alcanzar ese estado de forma mejor
  * `nodes_created`: Cuántos nodos de búsqueda se crearon. Los Nodos tienen un Estado y un poco más de información para la búsqueda, pero su relación no es 1:1 ya que varias veces vas a generar estados para los cuales ya tenías Nodos.
