### ISSUE TITLE
[Tarea 1] Duda IDDFS sin solucion

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#35]
Hola, queria saber como podriamos manejar el caso en que no haya solucion en IDDFS. Segun la implementacion de clases, si no hay solucioin, se podria quedar iterando eternamente. Sin embargo por el primer test pareciese que debemos manejar este caso. Sin embargo, me parece que no es tan directo saber hasta que profundidad explorar, ya que podemos quedarnos pegados viendo varios estados sin encontrar una solucion.

**Comment by Dietr1ch** [comment]
Creo que contesté parcialmente en https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Syllabus/issues/22#issuecomment-921274905.

> Segun la implementacion de clases, si no hay solucioin, se podria quedar iterando eternamente

Realmente depende del tamaño del grafo de estados, si es infinito, efectivamente puede suceder que te quedes iterando de forma infinita cuando no puedes alcanzar una solución incluso cuando exista una (podría haber una en la práctica ~infinitamente profunda o no?).


> Sin embargo por el primer test pareciese que debemos manejar este caso. 

El test tiene un espacio finito :)


> Sin embargo, me parece que no es tan directo saber hasta que profundidad explorar, ya que podemos quedarnos pegados viendo varios estados sin encontrar una solucion.

Es incorrecto terminar antes, pero es práctico tener límites. En la respuesta del otro issue detallo un poco más de cómo manejar esto.
