### ISSUE TITLE
Pregunta materia sobre consistencia de heurística

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#37]
Hola, no me quedó claro por qué el siguiente grafo no es consistente:
![image](https://user-images.githubusercontent.com/80859173/133711207-4f6bfc42-043a-44c2-b990-fc656441bf1a.png)

no logro encontrar el caso en que h(s) <= c(s, s') + h(s') no se cumple

Desde ya gracias, y buen 18!

**Comment by Dietr1ch** [comment]
Voy a nombrar los estados inicial y final como S y G, y el resto con el resto de las letras en orden desde izquierda a derecha y desde arriba a abajo.

B -> A

h(B) <=? c(B, A) + h(A)
20  >  5 + 12
20  > 17

**Comment by Dietr1ch** [comment]
Es el único estado para el que no se cumple, pero para ser justos los otros son triviales ya que el costo al estado que sigue ya es mayor o igual a la heurística, y además ese 20 es por lejos el valor más alto entre todos los estados.

**Comment by JuanpaBC** [comment]
muchas gracias!
