### ISSUE TITLE
Heurística Sokoban

### ISSUE THREAD

**Issue by nicoguz** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#38]
Hola!

Para la implementación de la primera heurística que se nos pide en sokoban debemos considerar (...)? o podemos simplemente calcular la distancia de cada caja a su objetivo más cercano sin importar (...)?

**Comment by Dietr1ch** [comment]
Hola!

Te agradecería tener más cuidado al preguntar, ya que originalmente diste detalles de tu tarea.

> Para la implementación de la primera heurística que se nos pide en sokoban debemos considerar (...)? o podemos simplemente calcular la distancia de cada caja a su objetivo más cercano sin importar (...)?

Del enunciado:
> Sokoban
> 
> El Sokoban es un puzzle en que un agente debe ordenar una bodega y ubicar cajas en algunas posiciones específicas.
> 
> En clases y ayudantías *mencionamos que una buena heurística es la de sumar las distancias de Manhattan entre cada caja y **su** objetivo más cercano.*

Esto es bastante específico, es simplemente la distancia de la caja a su objetivo más cercano

>   - [0.2] Implemente esta heurística.

Entonces tienen que implementarla

>   - [0.3] Notando que el agente tiene que acercarse a las cajas es fácil notar que falta contar acciones. Implemente esta versión mejorada de la heurística.

Mejorarla así.

>   - [0.7] Implemente una heurística estrictamente mejor que las anteriores.
>       - ¿Por qué su heurística es mejor?
>         - Agregue un test mostrando un estado en que:
>         - Su heurística sea mejor.
>         - Su heurística sea admisible. Use BFS para verificar el costo óptimo.

Y mejorarla aún más, en tu pregunta original ya mostrarste que sabes cómo hacerlo.
