### ISSUE TITLE
¿Hay código que resuelva un sudoku?

### ISSUE THREAD

**Issue by Zetaku1** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#39]
Hola,

Estaba leyendo la issue #13 sin embargo no entiendo que parte corresponde al sudoku. 
Deberíamos implementarlo nosotros mismos para testear o hay algo ya implementado?

Muchas gracias!

**Comment by Dietr1ch** [comment]
> Estaba leyendo la issue #13 sin embargo no entiendo que parte corresponde al sudoku.

Perdón, ahí debería decir Sokoban, el link estaba bien apuntando a `SokobanProblem::is_goal`. Lo acabo de arreglar.

>  Deberíamos implementarlo nosotros mismos para testear o hay algo ya implementado?

No, no está implementado, y tampoco necesitan una implementación del Sudoku para responder la pregunta.

**Comment by Zetaku1** [comment]
Gracias!
