### ISSUE TITLE
Duda Consistencia/Admisibilidad

### ISSUE THREAD

**Issue by imuoz** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#4]
No estoy seguro si entendí bien estos conceptos, así que prefiero preguntar si podrían explicármelo un poquito 😳.

**Comment by Huasito-Appel** [comment]
Lamento la demora Ignacio, esta semana lo veremos en la ayudantia (que es mas facil de explicar que por texto) de todas manera aca voy :   
## Admisibilidad : 
Una heuristica es admisible SSI para cada nodo n, h(n) ≤ h *(n), donde h *(n) significa el costo verdadero para llegar al estado meta n.   
Esto significa que una heuristica NUNCA sobreestima el costo de llegar al final, es decir si la heuristica perfecta para llegar desde un estado s hasta el estado final s* es 8, las heuristicas admisibles para ese problema deben estimar para el estado s un coste de 8 o menor, en general es dificil encontrar alguna que sea perfecta, ahi el truco, mantener admisibilidad intentando acercarse al optimo.   
## Consistencia
Una heuristica es consistente SSI   
- h(s) = 0 forall s subconjunto de G   
- h(s) <= c(s, s’) + h(s’) para todo vecino s’ de s   
- s = Padre, s’ = Hijo   
Esto quiere decir que para todo estado la funcion heuristica debe ser menor al costo real de llegar al objetivo por el camino hasta ese estado + el costo de las heuristicas de los nodos "hijos" ( o los sub-arboles si lo ves como arbol ) que salen a partir de ese estado. Esto implica que por ejemplo la funcion f(s) es estrictamente no decreciente para cualquier ruta.   
En palabras mas simples es que la heuristica no haga "trampa" y el costo de moverme desde B hasta objetivo sea el costo que me tomo llegar a B mas la estimacion de la heuristica en B.   
Algo NO consistente seria tener por ejemplo un puzzle de 8 en cierto estado y mover una pieza, que el coste de mover la pieza sea no nulo y que mi estimacion heuristica baje de manera no proporcinal.  (algo asi como que telatransportaste algunas piezas ) 
--> E_inicial = f(s) 8  = g(s) + h(s) ; g = 4, h = 2
--> movimiento costo 2
--->E_siguiente f(s) = 7 = g(s) = h(s); g = 5, h = 2 
## Tips
- Ver el final de la ayudantia pasada   
- ver este ejemplo donde ilustran una heuristica admisible pero no consistente (caso borde no trivial de entender) https://stackoverflow.com/questions/20516027/consistent-and-admissible-heuristics   
-  explicacion numerica https://www.youtube.com/watch?v=kAsVvS02T_U ( tiene media fea la letra pero es buen ejemplo) 
Eso, me cuentas si quedo mas claro, caso contrario dime nomas !
