### ISSUE TITLE
[Tarea 1]: ID-IDFS test_no_solution

### ISSUE THREAD

**Issue by crvargasu** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#40]
Hola,

En el [`test_no_solution()`](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/algorithms/iddfs_test.py#L37) se pide:

`assert iddfs.expansions == 22`

Pero me surge la duda, en ese caso estariamos contando solo las expansiones de la última iteración o no? entonces el test no debería ser así?

`assert iddfs.expansions  > 21`

**Comment by Dietr1ch** [comment]
Claro, ahora puedes calcular el número exacto también.

Probablemente el número real sea más cercano a 22*17/2 ya que en el último DFS vas a expandir 22 estados y va a ser de profundidad 17 (esto es asumiendo que se parece un poco a la suma de los primeros n números (1+2+3..+10 = 11*10/2)).

**Comment by crvargasu** [comment]
Entonces, como lo dejamos?

**Comment by Dietr1ch** [comment]
Es medio irrelevante, los tests de la evaluación van a ser otros.

Déjalo con el número exacto si quieres.

**Comment by crvargasu** [comment]
Gracias, quizás sea mejor dejar abierta la issue para q sepan todos del cambio en el test
