### ISSUE TITLE
Sokoban -  más boxes que goals

### ISSUE THREAD

**Issue by fnberrios** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#41]
Hola! Estaba revisando el main.py y al imprimir la cantidad de goals y boxes del ejemplo Sokoban entregado, resulta que hay más cajas que objetivos. ¿Es eso correcto? O ¿eso transforma el problema en infactible y nuestro código debería detectarlo?

Adjunto foto del ejemplo Sokoban suministrado por main
![image](https://user-images.githubusercontent.com/34272957/134071075-8ddddf04-3c60-46a5-9d56-c5dba9f8b872.png)

 y el resultado de la revisión de goals y boxes:
![image](https://user-images.githubusercontent.com/34272957/134070968-c16f43fa-eb0a-48f7-b722-62e453e9309f.png)

**Comment by Dietr1ch** [comment]
Ese problema no tiene solución, los algoritmos se "van a dar cuenta" luego de expandir algunos nodos.

La generación de problemas sin solución ocurre por un tratar de cumplir la "interfaz" (duck-typed) de MetaProblem. Ya se había reportado en #16, en donde se sugiere evitar generar problemas con `simple_given` para no caer en estos problemas triviales en los que puede costar más de lo necesario notar que no tienen solución.
