### ISSUE TITLE
Sokoban: Valor heurística en puzzles sin cajas.

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#42]
Tengo una duda sobre las box_positions de los states, y es que al probar los tests de Sokoban me aparecen como sets vacios, por lo que no se si es algo que deba implementar, o por qué podría estar pasando esto?
![Screenshot from 2021-09-20 18-44-23](https://user-images.githubusercontent.com/47841749/134080126-9f67af58-be59-4b67-8975-e90c69881988.png)
![Screenshot from 2021-09-20 18-44-13](https://user-images.githubusercontent.com/47841749/134080132-e2debbd2-a169-4c62-a7d9-4173c8212b80.png)

**Comment by VicenteMerino** [comment]
Pero, por qué estarían de forma trivial en un objetivo? Creo que eso no lo entiendo, ya que por lo que veo del test, las Sy las G están en posiciones distintas. Y de igual forma, me parece raro que las box_positions retornen un test vacío, y ese mismo problema me estaba pasando con test_heuristic_single_goal. De hecho, en ese la cantidad de Misplaced Boxes, debería ser 1 o no? En el test de ejemplo salía como 0.

**Comment by Dietr1ch** [comment]
> Pero, por qué estarían de forma trivial en un objetivo? Creo que eso no lo entiendo, ya que por lo que veo del test, las S las G están en posiciones distintas.

Ojo que el problema "dibujado" no es un ~laberinto, si no el puzzle de Sokoban, así que la instancia es extraña porque no hay cajas que mover. En la posición de `S` va a estar el agente y hay 2 lugares donde se pueden poner cajas.

Si estas instancias son un objetivo o no depende mucho de la forma de mirar el problema. Si el objetivo es que todas las cajas estén en un objetivo, entonces al no haber caja trivialmente "todas" las cajas están en un objetivo [por vacuidad](https://en.wikipedia.org/wiki/Vacuous_truth).

> no entendí qué es lo importante de esta issue, es un error lo que hay que corregir o una consideración a tomar en cuenta para este problema específico?

Sólo hay que notar que el test va a fallar porque una de las heurísticas de ejemplo retorna infinito si no hay cajas en vez de 0.
Pueden arreglar la heurística de ejemplo, pero la verdad no es necesario, sólo está allí para que mostrar cómo implementar heurísticas y cómo usarlas.


Que el test va a fallar y les va a parecer extraño. Una vez que se entiende que está malo es fácil arreglarlo

**Comment by JuanpaBC** [comment]
vale gracias!
