### ISSUE TITLE
[Tarea 1] Como llamar a A* y duda sobre tests actuales

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#43]
Hola, tengo una duda. Me parece que el código del test de A* llama a la clase, sin una heurística:

![image](https://user-images.githubusercontent.com/47841749/134111260-35a45848-770b-4ea6-8878-8fd6e2de8389.png)

Y me parece que es algo que si se debería incorporar, al igual que con Greedy:

![image](https://user-images.githubusercontent.com/47841749/134111302-bfb64701-4897-4d16-9736-92f9b6220f29.png)

Debemos cambiar esto? O el test deberia funcionar y llamarse tal como está?

Además tengo una duda sobre este y en general, todos los tests. Estos deberían funcionar, tal cual están? O debemos modificarlos para que calcen con los problemas que estamos resolviendo. Por ejemplo, en mi caso, con IDDFS me pasó que los tests se caían por los límites de tiempo, por lo cual se los cambié y pasaron. Es esto válido? O es un indicio de que mi implementación está mal?

**Comment by VicenteMerino** [comment]
Nevermind, me di cuenta que estaba la línea comentada (que pavo), pero igual si me responden mi segunda duda sería ideal.

**Comment by Dietr1ch** [comment]
> Debemos cambiar esto? O el test deberia funcionar y llamarse tal como está?

Claro, como la implementación que viene en realidad es Dijkstra hay que cambiar un poco cómo se inicializa A*, y el ejemplo que teníamos de `HeuristicSearchAlgorithm` es `Greedy` para demostrar cómo se usa esa clase base.


> Además tengo una duda sobre este y en general, todos los tests. Estos deberían funcionar, tal cual están? O debemos modificarlos para que calcen con los problemas que estamos resolviendo. Por ejemplo, en mi caso, con IDDFS me pasó que los tests se caían por los límites de tiempo, por lo cual se los cambié y pasaron. Es esto válido? O es un indicio de que mi implementación está mal?

Por favor trata de mantener los issues con un sólo tema.
Los tiempos dependen mucho de la máquina, lo único sospechoso es que se demoren demasiado poco, pero en realidad como contamos expansiones podríamos quitarlos de los tests, ya que hacen que los tests se vuelvan frágiles.
