### ISSUE TITLE
Bibliografía Tarea 1

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#44]
Hola, esperando que esten bien, tenía la duda de si quiero ocupar la primera forma de citar, mi bibliografía puede ir en un readme aparte para todo el código; y si es necesario referenciar de alguna manera que estoy ocupando fuentes exteriores en la parte correspondiente del código, como por ejemplo "#Revisar bibliografía 3". Desde ya gracias.

**Comment by Dietr1ch** [comment]
Puede ir en el documento de la tarea, junto con las repuestas a las preguntas que no son de código.

Está bien referenciar tu propio informe, así no tienes que mantener 2 copias.

**Comment by JuanpaBC** [comment]
Vale muchas gracias!
