### ISSUE TITLE
Python: ModuleNotFoundError con termcolor, numpy y pytest

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#47]
Hola,

me pasa que actualmente cuando corro códigos que importan alguno de los módulos "termcolor", "numpy", o "pytest", la terminal me dice que no encuentra estos módulos. Lo raro es que ya hice pip install con los tres módulos, y se supone que los tengo instalados.

Agradezco cualquier orientación.

**Comment by Dietr1ch** [comment]
Hola,

Puedes dar más información de esto? La verdad es que esencialmente dices "no me funciona", pero falta mucho contexto para poder entender qué está mal.
  * ¿Qué sistema operativo es?
  * ¿Cómo instalaste Python?
    * ¿Cuántas versiones de python tienes instaladas? ¿Sabes cuál te da error?.

`ModuleNotFoundError` parece claramente un problema de instalación.
Puedes ayudar a verificar que los módulos estén bien instalados? Deberían poder importarse en `python` o `ipython`.

**Comment by sofiaolmedos** [comment]
Hola yo tuve el mismo problema, y era porque vscode estaba corriendo en una versión de python diferente a donde tenía las librerías instaladas. Nunca antes había tenido este problema pero lo solucioné con esto https://www.py4u.net/discuss/153600

**Comment by FeBalla** [comment]
> Hola,
> 
> me pasa que actualmente cuando corro códigos que importan alguno de los módulos "termcolor", "numpy", o "pytest", la terminal me dice que no encuentra estos módulos. Lo raro es que ya hice pip install con los tres módulos, y se supone que los tengo instalados.
> 
> Agradezco cualquier orientación.

Me he encontrado con este error en otros semestres y, si bien no son las únicas opciones, generalmente se debe a que:
* No tienen agregado Python al ```PATH``` 
* Comprobar que el intérprete que esté usando tu IDE haga referencia al .exe real de Python. Una forma fácil de verlo es que al ejecutar un .py, el archivo de Python que use sea algo del estilo ```C:/Users/MyUser/AppData/Local/Programs/Python/Python38-32/python.exe``` y no del tipo ```C:/AlgunaCarpetaQueNoSeaLaDeInstalacion/python.exe```
* Por último, aunque menos común, que tenga que ver con algún problema de versiones

**Comment by JuanpaBC** [comment]
Al final pude resolver mi problema! Muchas gracias a todos los que me ayudaron, y sorry por no haber sido específico con la issue en el inicio. 

Por si alguien tiene el mismo problema que yo, dejo aquí resumidamente cómo al final llegué a la solución (como no sé cuáles pasos fueron los que en vdd hicieron la diferencia, les dejo todo el proceso por el que pase):

Tenía muchas versiones de python, las eliminé todas y me quede con una. En Editar las variables de entorno de esta cuenta (para poder modificar tienes que entrar desde Editar las variables de entorno de este sistema) anteriormente había puesto paths nuevos en la variable de sistema PATH siguiendo un video en yt para otro ramo (en edd quería hacer correr c en vsc), elimine esos paths que había puesto, y puse un path nuevo de la carpeta que tenía el python.exe de mi version nueva y única de python (3.9.6). La powershell y la cmd no me corrían pip hasta que reinicié el computador, y para entonces todo corría bn fuera de vsc (en powershell y cmd si me reconocía las librerías), solo en vsc todavía me pasaba lo mismo. Pregunté por el telegram de major compu, y me pasaron un link (https://stackoverflow.com/questions/56658553/module-not-found-error-in-vs-code-despite-the-fact-that-i-installed-it) donde encontré distintas posibles soluciones para mi problema, y la que a mi me sirvió fue la de escoger el interpretador de python correcto (el que estaba en el path de mi version nueva), porque aún habiendo desinstalado las otras versiones, vsc todavía ocupaba un interpretador de python antigüo. Y ahora me funcionan las librerías y todo en vsc.
