### ISSUE TITLE
A*: Desempates en la open

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#48]
Cuando se menciona en el enunciado que 

> Implemente desempates optimistas usando mayor g o menor h.

Yo elijo cual de las dos implementar, o debo implementar ambas?

**Comment by Dietr1ch** [comment]
Hay empates cuando los nodos tienen igual valor `f(n)`, que es `g(n)+h(n.state)`.

Si `f=g+h`, entonces preferir mayor `g` es lo mismo que preferir menor `h`
