### ISSUE TITLE
[Tarea 1]  Sudoku y heurística perfecta

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#49]
Hola, por qué se dice que en el problema de Sudoku conocemos a h*? Cuál sería esa heurística, o eso es algo que debemos pensar? O en realidad es como un "suponga que conoce h*"y que pese a eso A* no funciona bien?

**Comment by VicenteMerino** [comment]
Y en qué se diferencian la parte b y c? Encuentro que están preguntando cosas similares

> ¿Por qué A∗no es ideal para resolver sudokus?
¿Cómo se comporta A∗ con h∗ en este puzzle de costos uniformes?

**Comment by VicenteMerino** [comment]
I mean, para decir por qué A* debo decir cómo se comporta

**Comment by Dietr1ch** [comment]
Si, están muy relacionadas, las puedes contentar juntas. El objetivo es sólo que sean detallados en porqué A* funciona mal.
