### ISSUE TITLE
Problema al instalar termcolor 

### ISSUE THREAD

**Issue by tomasft0410** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#51]
Al correr el main me tira el siguente error:
![image](https://user-images.githubusercontent.com/48766029/134380940-66f9a3bc-d0f2-47ad-a041-31035210d8ab.png)
Entonces al tratar de instalar termcolor, ocurre lo siguente:
![image](https://user-images.githubusercontent.com/48766029/134381061-5ae7f73b-5c1b-47ee-8d42-d7e250ca51c1.png)
Porfavor si alguien sabe como solucionar este problema se agradeceria mucho!###

**Comment by FeBalla** [comment]
Como indica Juanpa, parece ser el mismo problema resuelto en #47 . Es probable que no estés usando el intérprete correcto de Python o que no tengas añadido Python al ```Path```. Te recomiendo revisar la otra _issue_ y si no logras solucionarlo con eso, volver a comentar.
