### ISSUE TITLE
[Tarea 1] Duda algoritmos híbridos

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#52]
Hola, si entiendo bien, aquí mi implementación de alfa-beta pruning incluye las tres propiedades y debo decir si correr primero alfa-beta y después MTCS, o primero MTCS y despues alfa-beta? O estoy entendiendo algo mal?

**Comment by Huasito-Appel** [comment]
Exacto, la idea es que desarolles uno que utilice lo mejor de ambos mundos y se ajuste segun la evolucion del problema.
