### ISSUE TITLE
[Tarea 1] Nodos a explorar

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#53]
En esta pregunta, podemos responder usando notación asintótica, o debemos dar el valor exacto?

**Comment by FeBalla** [comment]
> En esta pregunta, podemos responder usando notación asintótica, o debemos dar el valor exacto?

Este curso no tiene como requisito Matemáticas Discretas ni EDD, así que preferimos no exigir esa notación. Ahora, con respecto a tu pregunta, no me termina de quedar claro a qué te refieres con "valor exacto", ya que obtener una expresión matemática que modela la cantidad de nodos a explorar es muy similar a pedir la notación asintótica en este caso.

Me refiero a que si yo tuviera que, por ejemplo, recorrer todos los nodos de un árbol binario, por cada nivel hay 2^n nodos (donde n es el nivel) y el saber cuántos nodos hay es **prácticamente equivalente** a hablar de su complejidad. Ahora, si te refieres a ponernos en el peor caso, efectivamente es ese el acercamiento esperado, ya que posibilidades intermedias pueden haber muchas. 

Espero haber respondido tu pregunta y si no, puedes volver a comentar 😃

**Comment by VicenteMerino** [comment]
Si, con cantidad exacta me refiero con la expresión matemática que modele la cantidad de nodos. Entonces debo dar mi respuestas de la forma cantidad_nodos(b, d) = f(b, d)  (siendo f alguna expresión)?

**Comment by FeBalla** [comment]
Claro, finalmente lo que se busca con esta pregunta es que se abstraigan a un árbol de juego cualquiera (con las características dadas) y piensen sobre cómo van explorando los distintos algoritmos.
