### ISSUE TITLE
[Tarea 1] Tests Sokoban en un solo test

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#54]
Hola, es posible mostrar los requerimientos de que mi heuristica sea mejor y que sea admisible en un solo test?

**Comment by Huasito-Appel** [comment]
si es posible, deja anotado en el readme nomas todas esas cosas para que no tengamos problemas al corregir.

**Comment by Dietr1ch** [comment]
Si, pero en general es mejor tener más tests simples a que uno que termine siendo muy complejo.
