### ISSUE TITLE
Duda heurística estrictamente mejor en sokoban

### ISSUE THREAD

**Issue by festelle** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#55]
Qué significa que una heurística sea estrictamente mejor que las anteriores? Esta heurística tiene que dar un mejor resultado en cualquier escenario o solo es necesario que dé resultados iguales [que las heurísticas hechas antes] en general y un resultado mejor en alguna situación en particular?

**Comment by Huasito-Appel** [comment]
Significa que en la mayoria de los los escenarios debe dar un mejor resultado, ya que puede darse que para un problema en particular la heuristica "peor" termine funcionando de mejor manera.

**Comment by Dietr1ch** [comment]
Claro.

Ahora, en este caso no es difícil obtener una heurística consistente que sea estrictamente mejor que las propuestas (o sea >= que las propuestas), puedes mostrar que al menos considera las acciones que las heurísticas propuestas consideran, y que en algunos casos aproxima mejor a h*
