### ISSUE TITLE
Cómo implementar ID-DFS

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#56]
No entiendo bien en qué archivo hay que trabajar para implementar ID-DFS y si es que quieren que lo iniciemos desde cero o hay que llamarlo desde otro archivo.py

**Comment by Dietr1ch** [comment]
Hay un stub en [search/algorithms/iddfs.py](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/tree/assignment/search/algorithms/iddfs.py)

Deberían poder reutilizar la implementación de DFS, pero van a tener que extenderla para que soporte límite de profundidad.
