### ISSUE TITLE
Búsqueda con Adversarios: Justificación

### ISSUE THREAD

**Issue by baosse** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#57]
Holaa! 
Me surgió la duda de cómo debía realizar la justificación para las preguntas de búsquedas con adversarios, en donde se pregunta cual sería el mejor y peor caso. Es necesario buscar una fórmula o si lo explico bonito (jaja) y entendible estará bien?

**Comment by Huasito-Appel** [comment]
Como no pedimos discretas no es necesaria una demostracion formal, como tu dices una explicacion bonita, en donde menciones en notacion O, que explique que es lo que sucede en cada caso y por que es asi basta.

**Comment by Dietr1ch** [comment]
Pueden describir el mejor caso y dar cotas razonables para la cantidad de nodos expandidos.
