### ISSUE TITLE
Implementación de la heurística de Manhattan en puzle de 15 (Tarea 1)

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#59]
Hola profes, en el método __call__ de la clase NMPuzzleManhattanDistance (nm_puzzle.py), para poder implementar la heurística supongo que contamos con el parámetro state para obtener las posiciones de las locetas, y con la función manhattan_distance_2d. Tengo dos dudas al respecto:

- self.problem.goal_states contiene un grid del puzle ordenado? buscando en el código llegué a que este atributo es de tipo Sequence[NMPuzzle.State], y en internet lo más que cache fue que Sequence es un set ordenado, pero en este punto me perdí porque no entiendo cómo una clase se puede convertir en un set, por lo que tampoco comprendo qué es en sí el atributo self.problem.goal_states ni cómo ocuparlo.

- el parámetro state, de clase NMPuzzle.State, leyendo la parte de arriba del código, donde se define esta clase, intuyo que nos servirá para obtener las posiciones de las locetas del estado particular mediante su atributo grid, pero mi problema es con el tipo de este atributo, ndarray o n-dimentional array de la librería numpy. Busqué en internet pero no me quedó claro la descripción de esta clase, donde más caché fue en el método __init__ de NMPuzzle.State cuando itera sobre los elementos de self.grid para buscar el max_x y max_y, pero tampoco me quedó muy clara su estructura. np.ndarray es una lista de tuplas del estilo [ ( num_fila, [ ( num_col, valor en posición num_fila, num_col ) ] ) ] ? como por ejemplo [ ( 1 , [ (1, 14) , (2, 6) , (3, 7) , (4, 1) ] ) , ( 2 , [ (1, 9) , (2, 2) , (3, 11) , (4, 13) ] ) , ( 3, ... ), (4, ... ) ] ?

Desde ya gracias

**Comment by Dietr1ch** [comment]
(Estas dudas que en realidad son muchas dudas en un sólo issue son en general malas preguntas, ya que nadie más va a poder leer el título del issue y saber si acá contestan algo en específico que les pueda servir.)


> Hola profes, en el método **call** de la clase NMPuzzleManhattanDistance (nm_puzzle.py), para poder implementar la heurística supongo que contamos con el parámetro state para obtener las posiciones de las locetas,

Claro, esto viene desde la interfaz de [Heuristic](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/space.py#L159)
y con la función [manhattan_distance_2d](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/problems/nm_puzzle.py#L248). Tengo dos dudas al respecto:
> 
>     * self.problem.goal_states contiene un grid del puzle ordenado? buscando en el código llegué a que este atributo es de tipo Sequence[NMPuzzle.State], y en internet lo más que cache fue que Sequence es un set ordenado,

No es un Set, pueden haber duplicados, y puede ser una corrutina. Si tienes problemas con esto te recomiendo revisar la documentación de [pytype](https://google.github.io/pytype/)

pero en este punto me perdí porque no entiendo cómo una clase se puede convertir en un set,

No es lo que está pasando, la anotación de `-> Sequence[NMPuzzle.State]` dice que una función retorna una secuencia de `NMPuzzle.State`s.

por lo que tampoco comprendo qué es en sí el atributo self.problem.goal_states ni cómo ocuparlo.

Las anotaciones de tipos en python son opcionales, por lo que si las ignoras no cambia el programa. Por lo tanto, no puede ser por culpa de ellas que no entiendas self.problem.goal_states. Tu problema es que no entiendes [`NMPuzzleProblem`](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/problems/nm_puzzle.py#L215-L231), te recomiendo leerla.
En general antes de tratar de entender cada member y submember de una clase, es mejor tratar de entender a más alto nivel la clase que tiene al member, así como las interfaces que la clase implementa (o de las clases que hereda).


>     * el parámetro state, de clase NMPuzzle.State,
No hay un parámetro state en [NMPuzzle.State](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/problems/nm_puzzle.py#L45-L60), la clase completa es un Estado.

>  leyendo la parte de arriba del código, donde se define esta clase, intuyo que nos servirá para obtener las posiciones de las locetas del estado particular mediante su atributo grid, pero mi problema es con el tipo de este atributo, ndarray o n-dimentional array de la librería numpy. 

`ndarray` es la abreviación de N-dimensional array, En este caso usamos una matriz 2D de NxM que representa al tablero.
También es una de las clases más básicas de numpy, así que está bien documentado.

Busqué en internet pero no me quedó claro la descripción de esta clase, donde más caché fue en el método `__init__` de `NMPuzzle.State` cuando itera sobre los elementos de `self.grid` para buscar el `max_x` y `max_y`, pero tampoco me quedó muy clara su estructura. np.ndarray es una lista de tuplas del estilo [ ( num_fila, [ ( num_col, valor en posición num_fila, num_col ) ] ) ] ? como por ejemplo [ ( 1 , [ (1, 14) , (2, 6) , (3, 7) , (4, 1) ] ) , ( 2 , [ (1, 9) , (2, 2) , (3, 11) , (4, 13) ] ) , ( 3, ... ), (4, ... ) ] ?

El atributo `grid` de NMPuzzle.State es simplemente una matriz de NxM, y estoy seguro que tomar el [test de `NMPuzzle`](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/problems/nm_puzzle_test.py) como referencia para o usar el intérprete de Python (o `ipython`) para inspeccionar los objetos y funciones, o incluso crear un programa pequeño si es que te resulta más fácil que usar el intérprete.

Me gustaría que formules mejor tus preguntas.
