### ISSUE TITLE
Sokoban: Duda heurística Manhattan

### ISSUE THREAD

**Issue by pedro919** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#60]
Hola, en el Sokoban tengo una duda con respecto a la primera heurística que debemos implementar.
El enunciado dice: "En clases y ayudantías mencionamos que una buena heurística es la de sumar las distancias de
Manhattan entre cada caja y su objetivo más cercano." Sin embargo no se que hacer en el caso de que hayan más cajas que objetivos.

Por ejemplo si tengo 3 cajas y 1 objetivo, debo considerar la distancia de Manhattan de las 3 cajas al objetivo o solo la caja más cercana?

**Comment by maggiemunoz** [comment]
Tengo entendido que en el caso de tener más cajas que objetivos la distancia sería infinita, ya que no hay solución. Agradecería que algún ayudante o el profe confirme ya que ahora me entró la duda a mí jajaja

**Comment by Dietr1ch** [comment]
> El enunciado dice: "En clases y ayudantías mencionamos que una buena heurística es la de sumar las distancias de
> Manhattan entre cada caja y su objetivo más cercano." Sin embargo no se que hacer en el caso de que hayan más cajas que objetivos.

Aunque hayan más cajas que objetivos está bien definida la suma entre las cajas y su objetivo más cercano.
Ahora, también es razonable ir más allá y retornar infinito para mostrar que no se puede alcanzar el objetivo desde ese estado, pero esa sería una heurística distinta a la que se está pidiendo.
