### ISSUE TITLE
Heuristica de manhattan contando acciones

### ISSUE THREAD

**Issue by Coolgatty** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#61]
Hola! En la heuristica de manhattan contando acciones tengo una duda de como funciona el sokoban.
Ejemplo si tengo:

"S BG"  la distancia de S a B es 2 pero el agente puede empujar la caja desde la casilla anterior o debe ponerse en la misma casilla que la caja para moverla?

Mi duda es como debo contar la distancia entre S y B

**Comment by maggiemunoz** [comment]
Venia a hacer esta misma pregunta, yo estoy asumiendo que la distancia entre S y B en ese caso sería 1, ya que el agente no puede pararse encima de la caja, agradecería si pueden confirmar que distancia es la correcta :)

**Comment by Dietr1ch** [comment]
> Hola! En la heuristica de manhattan contando acciones tengo una duda de como funciona el sokoban.
> Ejemplo si tengo:
> 
> "S BG" la distancia de S a B es 2 pero el agente puede empujar la caja desde la casilla anterior

Exacto, es por la misma consideración de que se habla de que el agente tiene que poder empujar la caja

**Comment by andrescf** [comment]
Hola! Pero si una caja tiene 4 espacios disponibles alrededor (arriba, abajo, izquierda y derecha), como sabemos a cual calcular la distancia? Porque dependiendo de como defina eso las heuristicas serian diferentes y puedo elegir la menor distancia para estar en una posicion para empujar pero no significa que pueda empujarla o que sea la direccion correcta en que se tenga en empujar.
