### ISSUE TITLE
Sokoban: error en métricas cuando una solución tiene costo 0

### ISSUE THREAD

**Issue by jiaranda** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#62]
Tengo un problema al ejecutar el programa completo cuando hay un puzzle de sokoban con 0 cajas:

Cuando no hay cajas, el algoritmo entrega una solución con costo 0, lo que creo que tiene sentido siguiendo la lógica de [esta issue](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Syllabus/issues/42#issuecomment-924050427). Luego, en el [archivo main](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/d7e7fca6b93c3ad9e1a8cc0a5a4958988bf01c61/main.py#L87-L104) se comparan los resultados de los algoritmos y se almacenan los mejores valores (en este caso, el costo 0). Finalmente, para mostrar los resultados [se divide por este valor](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/d7e7fca6b93c3ad9e1a8cc0a5a4958988bf01c61/main.py#L115), generando un error de división por 0.

Este es el error que tengo:
```
Traceback (most recent call last):
  File "main.py", line 316, in <module>
    main()
  File "main.py", line 312, in main
    compare(algorithms, problem, heuristic_class)
  File "main.py", line 115, in compare
    "{:.2%}".format(solution["cost"] / best["cost"]),
ZeroDivisionError: division by zero
```

Mi duda es: ¿yo no debería estar entregando un costo 0 o el main no está manejando bien los valores?

**Comment by Dietr1ch** [comment]
> Tengo un problema al ejecutar el programa completo cuando hay un puzzle de sokoban con 0 cajas:
> 
> Cuando no hay cajas, el algoritmo entrega una solución con costo 0, lo que creo que tiene sentido siguiendo la lógica de [esta issue](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Syllabus/issues/42#issuecomment-924050427). Luego, en el [archivo main](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/d7e7fca6b93c3ad9e1a8cc0a5a4958988bf01c61/main.py#L87-L104) se comparan los resultados de los algoritmos y se almacenan los mejores valores (en este caso, el costo 0). Finalmente, para mostrar los resultados [se divide por este valor](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/d7e7fca6b93c3ad9e1a8cc0a5a4958988bf01c61/main.py#L115), generando un error de división por 0.
> 
> Este es el error que tengo:
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 316, in <module>
>     main()
>   File "main.py", line 312, in main
>     compare(algorithms, problem, heuristic_class)
>   File "main.py", line 115, in compare
>     "{:.2%}".format(solution["cost"] / best["cost"]),
> ZeroDivisionError: division by zero
> ```
> 
> Mi duda es: ¿yo no debería estar entregando un costo 0 o el main no está manejando bien los valores?

Es un problema del main, maneja el caso de 0 en las otras métricas, pero no en el costo.

**Comment by ignaciomansuy** [comment]
@Dietr1ch hacemos algo específico para arreglarlo o nos las arreglamos con un `try:    except ZeroDivisionError` ?
