### ISSUE TITLE
Crear test para sokoban

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#64]
Hola!

Me entró una duda con la redacción del enunciado, en la parte de Sokoban este dice,

> Agregue un test mostrando un estado en que:
>   * Su heurística sea mejor.
>   * Su heurística sea admisible. Use BFS para verificar el costo óptimo."

entonces yo justamente cree un test con un estado que demuestra eso, pero leyendo otras issues (específicamente la #33) me di cuenta que con otros estados iniciales algunas de mis heurísticas no son admisibles. Entonces mi duda es, tengo que arreglar mis heurísticas para que sean admisibles en todos los estados posibles o con tener que el test muestre un estado en el que cumple lo pedido está bien

**Comment by Dietr1ch** [comment]
> Hola!
> 
> Me entró una duda con la redacción del enunciado, en la parte de Sokoban este dice,
> 
> > Agregue un test mostrando un estado en que:
> > 
> > * Su heurística sea mejor.
> > * Su heurística sea admisible. Use BFS para verificar el costo óptimo."
> 
> entonces yo justamente cree un test con un estado que demuestra eso, pero leyendo otras issues (específicamente la #33) me di cuenta que con otros estados iniciales algunas de mis heurísticas no son admisibles.
> Entonces mi duda es, tengo que arreglar mis heurísticas para que sean admisibles en todos los estados posibles o con tener que el test muestre un estado en el que cumple lo pedido está bien

tl;dr: Tienes que arreglar tu heurística.

La admisibilidad es una propiedad que se tiene que cumplir para todos los estados, pedimos un ejemplo en un estado en particular para que muestren que funciona y que al menos para algún estado cumple admisibilidad, pero eso no es suficiente para demostrar Admisibilidad en todos los estados.

Cumplir admisibilidad tampoco te asegura que tu heurística ayude a A* a encontrar soluciones óptimas, por lo que la propiedad que realmente quieres poder demostrar es que tu heurística sea Consistente.
