### ISSUE TITLE
[Tests] Problema al correr los tests: Invalid Syntax

### ISSUE THREAD

**Issue by pedro919** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#65]
Hola, estoy teniendo problemas a la hora de correr los tests. Me tira invalid sytax por algunos argumentos en funciones que ya venían definidas.

![pantallazo3](https://user-images.githubusercontent.com/42246537/134830244-4fd38203-e79d-45fd-a1d5-da29dbbd076d.png)
 
Como puedo arreglar esto o que estoy haciendo mal?

**Comment by Dietr1ch** [comment]
Estás usando Python 2 allí, el código usa sintáxis nueva de Python 3 (al menos 3.5) introducida en [PEP483](https://www.python.org/dev/peps/pep-0483/) (y varios más) y la librería [`typing`](https://docs.python.org/3/library/typing.html).

Python 2 fue deprecado hace más de un año (https://pythonclock.org/). La tarea asume que usan Python 3.8 o superior, pero creo que Python 3.7 también funciona.
