### ISSUE TITLE
Arbol de juego con b ramas por nivel y profundidad d

### ISSUE THREAD

**Issue by Coolgatty** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#66]
Hola estoy medio confundido con lo que se refiere que hay un Arbol de juego con b ramas por nivel y profundidad d.
Significa que cada nodo tiene b hijos o que en total todos los hijos del nivel suman b? 

Todos los nodos tienen la misma cantidad de hijos?

**Comment by FeBalla** [comment]
Hola, se refiere a que cada nodo tiene b hijos
