### ISSUE TITLE
Implementacion de Sokoban y Goals ocupados

### ISSUE THREAD

**Issue by andrescf** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#68]
Buenas tardes!

Tengo una duda sobre como implementar las heuristicas de sokoban ya que comentando [el enunciado](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Assignment-1/releases/download/v0.4-alpha/assignment-search.pdf) con un amigo lo interpretamos de formas diferentes, para el [SimpleDistance](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/problems/grid/sokoban.py#L357) yo entendi que hay que buscar la distancia al objetivo mas cercano de cada caja pero luego de ocupar un objetivo se descarta porque ya estara ocupado por esa caja y no deberia llevar 2 cajas a un mismo objetivo.

Luego en ActionDistance no entiendo como se puede elegir a que posicion respecto de la caja se debe mover el agente porque si elijo la mas cercana puede que no sea una posicion en la que despues se pueda mover, por lo que la distancia valida mas cercana seria otra. Ademas, al mover un agente hacia una caja entiendo que se debe actualizar el valor de la posicion del agente para despues calcular la distancia desde la nueva posicion hacia la caja mas cercana pero mi amigo me dice que es desde la posicion original del agente hacia todas las cajas y no considerando el camino que debe hacer.

Espero que se entiendan mis dudas,
Gracias

**Comment by Dietr1ch** [comment]
Hola,


> Tengo una duda sobre como implementar las heuristicas de sokoban ya que comentando [el enunciado](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Assignment-1/releases/download/v0.4-alpha/assignment-search.pdf) con un amigo lo interpretamos de formas diferentes, para el [SimpleDistance](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/assignment/search/problems/grid/sokoban.py#L357) yo entendi que hay que buscar la distancia al objetivo mas cercano de cada caja pero luego de ocupar un objetivo se descarta porque ya estara ocupado por esa caja y no deberia llevar 2 cajas a un mismo objetivo.

No es así, la heurística propuesta es una aproximación muy simple, y no se preocupa de que esté mal pensar que varias cajas puedan terminar en el misma casilla objetivo.


> Luego en ActionDistance no entiendo como se puede elegir a que posicion respecto de la caja se debe mover el agente porque si elijo la mas cercana puede que no sea una posicion en la que despues se pueda mover, por lo que la distancia valida mas cercana seria otra.

Nuevamente, esta heurística también es una aproximación simple, y no se preocupa de que efectivamente tengas que mover esa caja, incluso podría ser una caja que ya está en su objetivo, o estar considerando llegar a una casilla que no sea alcanzable (en el caso de que haya un muro entre la caja y el agente.

> Ademas, al mover un agente hacia una caja entiendo que se debe actualizar el valor de la posicion del agente

No, esta heurística es una función matemática, no debería modificar el estado por el que te preguntan su valor. Si lo haces vas a modificar el estado interno de tu búsqueda y sería muy poco probable que los algorimos sigan funcionando bien.

**Comment by andrescf** [comment]
> 
> Nuevamente, esta heurística también es una aproximación simple, y no se preocupa de que efectivamente tengas que mover esa caja, incluso podría ser una caja que ya está en su objetivo, o estar considerando llegar a una casilla que no sea alcanzable (en el caso de que haya un muro entre la caja y el agente.

¿El considerar eso no haría que la heurística no fuera admisible? Ya que, por ejemplo, si tenemos X goals con sus cajas encima y solo nos faltara mover una caja un solo espacio la heurística calcularía la distancia del agente hacia todas cajas obteniendo un valor estimado mayor al real.

**Comment by Dietr1ch** [comment]
> > Nuevamente, esta heurística también es una aproximación simple, y no se preocupa de que efectivamente tengas que mover esa caja, incluso podría ser una caja que ya está en su objetivo, o estar considerando llegar a una casilla que no sea alcanzable (en el caso de que haya un muro entre la caja y el agente.
> 
> ¿El considerar eso no haría que la heurística no fuera admisible? Ya que, por ejemplo, si tenemos X goals con sus cajas encima y solo nos faltara mover una caja un solo espacio la heurística calcularía la distancia del agente hacia todas cajas obteniendo un valor estimado mayor al real.

No, ojo que si bien consideramos que hay que mover cada caja a su goal más cercano, al considerar que el agente tiene que llegar a una caja sólo consideramos una de las cajas (y la más cercana).

Por ejemplo acá (usando puntos en vez de espacios para ayudar a contar)
La caja de la izquierda que está en su goal (`! `) agrega 0, la caja de la derecha agregaría 1, y como el agente está al lado de su caja más cercana no se tendría que mover para poder empujarla (aún cuando esa caja no es la que se necesita empujar). Con esto la heurística daría un costo estimado de 1, que es admisible ya que el costo real, h*, es de 2

```
#!a BG
```

**Comment by andrescf** [comment]
> > > Nuevamente, esta heurística también es una aproximación simple, y no se preocupa de que efectivamente tengas que mover esa caja, incluso podría ser una caja que ya está en su objetivo, o estar considerando llegar a una casilla que no sea alcanzable (en el caso de que haya un muro entre la caja y el agente.
> > 
> > 
> > ¿El considerar eso no haría que la heurística no fuera admisible? Ya que, por ejemplo, si tenemos X goals con sus cajas encima y solo nos faltara mover una caja un solo espacio la heurística calcularía la distancia del agente hacia todas cajas obteniendo un valor estimado mayor al real.
> 
> No, ojo que si bien consideramos que hay que mover cada caja a su goal más cercano, al considerar que el agente tiene que llegar a una caja sólo consideramos una de las cajas (y la más cercana).
> 
> Por ejemplo acá (usando puntos en vez de espacios para ayudar a contar) La caja de la izquierda que está en su goal (`!`) agrega 0, la caja de la derecha agregaría 1, y como el agente (`a`) está al lado de su caja más cercana, no se tendría que mover para poder empujarla (aún cuando esa caja no es la que se necesita empujar). Con esto la heurística daría un costo estimado de 1, que es admisible ya que el costo real, h*, es de 2
> 
> ```
> #!a.BG
> ```

Perfecto, ahi me quedo mucho mas claro. Gracias!

**Comment by Dietr1ch** [comment]
Bueno, la última heurística propuesta puede ser inadmisible en casos medios inesperados, ya que asume que HAY que acercarse a alguna caja.

Si el agente luego de solucionar un problema se aleja de las cajas sin mover ninguna, entonces la heurística estaría sobre-estimando el valor, ya que no falta arreglar ninguna caja, sin embargo el agente si tendría que moverse.

La solución simple es tener un early-return con 0 para estados objetivos, y una más correcta es ignorar las cajas que están en algún objetivo al considerar que el agente debe empujar alguna, pero este error es en parte para hacer que mejorar las heurísticas propuestas no sea tan difícil.
