### ISSUE TITLE
Problema con commit hooks

### ISSUE THREAD

**Issue by domingo2000** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#69]
Hola, estaba tratando de hacer commit con el commit hook y me arroja lo siguiente 
![image](https://user-images.githubusercontent.com/40220174/135181058-bd73d4da-c758-496f-ac32-08c95ba60028.png)
Que debo hacer??

**Comment by Dietr1ch** [comment]
Es un problema del ambiente de tu shell.

Puedes cambiar el [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) y buscar `python3` en vez de `python`.
O simplemente cambiar el hook local (en `.git/hooks/pre-commit`) para que en vez de correr `./main.py` corra `python3 main.py`.
