### ISSUE TITLE
[Tarea 1] Problema clonar repo

### ISSUE THREAD

**Issue by cjones27** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#7]
Hola! Estoy teniendo un problema al clonar el repo. Ya lo inicialicé y el [remoto](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/tarea-1-2021-2-cjones27) está creado. Revisé una actualización de la forma de autenticación de GitHub y a pesar de actualizarlo aún no puedo clonarlo. Adjunto error.

>  git clone https://github.com/IIC2613-Inteligencia-Artificial-2021-2/tarea-1-2021-2-cjones27.git
Cloning into 'tarea-1-2021-2-cjones27'...
remote: Repository not found.
fatal: repository 'https://github.com/IIC2613-Inteligencia-Artificial-2021-2/tarea-1-2021-2-cjones27.git/' not found

Muchas gracias de antemano

**Comment by cjones27** [comment]
Al final logré arreglarlo. Fue un problema de configuración de autenticación con GitHub (quizás debido al update). Lo solucioné configurando una ssh-key con GitHub siguiendo esta [guía](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent). OS: macos

**Comment by FeBalla** [comment]
> Al final logré arreglarlo. Fue un problema de configuración de autenticación con GitHub (quizás debido al update). Lo solucioné configurando una ssh-key con GitHub siguiendo esta [guía](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) por si a alguién le sirve. OS: macos

Perfecto! Gracias por comentar tu solución

**Comment by sebaew98** [comment]
Hola!, tengo el mismo problema y estoy tratando de seguir la guia pero no logro solucionar el problema, ayuda porfavorr 
![Screen Shot 2021-09-15 at 15 11 36](https://user-images.githubusercontent.com/62079275/133486944-d4a4c773-2ea3-401f-9396-eb39f9035d73.png)

**Comment by cjones27** [comment]
Haz `sudo <comando>`

**Comment by sebaew98** [comment]
ya lo solucione! descague git para el computador, inicie sesion y 0 problemas!
