### ISSUE TITLE
[Tarea 1] Error en test_tie_breaking en A* 

### ISSUE THREAD

**Issue by cncosta** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#70]
Hola, al correr el test de tie breaking en A* me aparece el siguiente error:
```shell
>       assert node_1 < node_2
E       assert <search.algorithms.astar.AStar.AStarNode object at 0x000002055EF52100> < <search.algorithms.astar.AStar.AStarNode object at 0x000002055EF52130>
```
Por alguna razón no reconoce bien el resultado y arroja la dirección de memoria de los dos objetos que se están comparando.

**Comment by JDomingoSilva** [comment]
Me pasa lo mismo

**Comment by Dietr1ch** [comment]
Qué curioso que `assert a < b` falle, pero que puedan hacer,

```python
is_less_than = a < b
assert is_less_than  # == True
```


¿Qué versión de Python están usando?

El ambiente de nix de la tarea usa Python 3.8 y todos los tests pasan, pero lo raro es que `__lt__` es una función bastante vieja en Python.

**Comment by cncosta** [comment]
Si a mi también me parece super raro el error, pero con la variable se soluciona o por lo menos podemos testear la función.
 Mi versión de python es 3.8.10.
Lo extraño fue que al comienzo no arrojaba ese error y cuando edité ``` __lt__``` de [A*](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/d7e7fca6b93c3ad9e1a8cc0a5a4958988bf01c61/search/algorithms/astar.py#L68) comenzó a mostrar el resultado como representación de objeto y no como ```bool```. 
¿puede se quizas error del modulo pytest o del interpreter de Visual Studio?

**Comment by Dietr1ch** [comment]
> Si a mi también me parece super raro el error, pero con la variable se soluciona o por lo menos podemos testear la función. Mi versión de python es 3.8.10. Lo extraño fue que al comienzo no arrojaba ese error y cuando edité ` __lt__` de [A*](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Search-py/blob/d7e7fca6b93c3ad9e1a8cc0a5a4958988bf01c61/search/algorithms/astar.py#L68) comenzó a mostrar el resultado como representación de objeto y no como `bool`. ¿puede se quizas error del modulo pytest o del interpreter de Visual Studio?


Yo apostaría a que es un error de tu implementación. En vez de retornar `True`/`False` intenta retornar una comparación.

Cuidado que en Python no retornar, en vez de razonablemente ser un error, equivale a retornar `None` en esos /codepaths/.
