### ISSUE TITLE
[Tarea 1] Commit hooks

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#71]
Hola, quería saber si es estrictamente necesario habilitar los hooks? En el enunciado como decía que era una recomendación no le tomé mucha importancia, por lo que solo me preocupé de usar black antes de cada commit. Basta con que mis codigo pase `black .` y `pytest` al correrlos en la raíz? O debo habilitar los commit hooks? Existe alguna penalización en caso de no hacerlo?

**Comment by Dietr1ch** [comment]
> Hola,
> quería saber si es estrictamente necesario habilitar los hooks? En el enunciado como decía que era una recomendación no le tomé mucha importancia, por lo que solo me preocupé de usar black antes de cada commit
> Basta con que mis codigo pase `black .` y `pytest` al correrlos en la raíz?

Si es una recomendación porque sólo nos importa el commit final, y pueden simplemente hacer eso antes de entregar sin haber usado nunca los hooks.
