### ISSUE TITLE
[Tarea 2] Cambio en archivo base de Dependency-Hell

### ISSUE THREAD

**Issue by matumartinez** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#73]
Hola!

Podría cambiar las siguientes lineas de 0.lp (dependency Hell):

```
requiresAtLeast(echo, libc, 1).  % `echo` uses new feature from libc v1.
requiresAtLeast(ls, libc, 0).
requiresAtMost(cat, libc, 2).    % libc v3 broke `cat`.
```

A:

```
requiresAtLeast(program(echo), libc, 1).  % `echo` uses new feature from libc v1.
requiresAtLeast(program(ls), libc, 0).
requiresAtMost(program(cat), libc, 2).    % libc v3 broke `cat`.
```

Creo que hace más sentido de la segunda manera y facilita establecer la lógica posterior.

**Comment by Dietr1ch** [comment]
> Hola!
> 
> Podría cambiar las siguientes lineas de 0.lp (dependency Hell):
> 
> ```
> requiresAtLeast(echo, libc, 1).  % `echo` uses new feature from libc v1.
> requiresAtLeast(ls, libc, 0).
> requiresAtMost(cat, libc, 2).    % libc v3 broke `cat`.
> ```
> 
> A:
> 
> ```
> requiresAtLeast(program(echo), libc, 1).  % `echo` uses new feature from libc v1.
> requiresAtLeast(program(ls), libc, 0).
> requiresAtMost(program(cat), libc, 2).    % libc v3 broke `cat`.
> ```
> 
> Creo que hace más sentido de la segunda manera y facilita establecer la lógica posterior.

No, ya que los test cases también tendrían que considerar esos cambios.

Tu propuesta si bien parece leerse mejor, la verdad se vuelve algo extraña,
  * Ahora `program(X)` ya no es un predicado, si no que una función que retorna un objeto, con lo que cambias también el dominio de `requiresAtLeast`/`requiresAtMost` con los que se describe el input.
  * Tener un predicado `program` permite que los objetos sean múltiples cosas al mismo tiempo, pero al tratar de hacerlo así te generaría problemas ya que tendrías que establecer un órden de cómo usar todos los predicados. (`perro(mascota(X))` o `mascota(perro(X))`).
