### ISSUE TITLE
Cómo van a probar la tarea?

### ISSUE THREAD

**Issue by matumartinez** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#75]
Hola!

Me surgió la duda de cómo se va a probar y ejecutar la tarea. ¿Hay que editar los 0.lp o los otros archivos? ¿Y por ejemplo para el dependency hell siempre va a ser con la librería "libc" o tenemos que hacer el programa para probar cualquier input que pongan?

**Comment by Dietr1ch** [comment]
Tal como lo hicimos en clases. Vamos a tener un modelo, que en el caso de planning va a también incluir la versión de STRIPS adecuada, y una instancia.


Por ejemplo,

```
clingo \
  --models $MODELS \
  csat/dep_hell/dh.lp \
  csat/dep_hell/instances/secret-0.lp \
```

```
clingo \
  --const "k=$LIMIT" \
  --models $MODELS \
  planning/strips-multiagent.lp \
  planning/coffee/coffee-multiagent.lp \
  planning/statues/instances/secret-0.lp 
```


Ahora, en la práctica, vamos a asegurarnos de que los programas corran dentro de cierto tiempo razonable también, usando `timeout` con un soft-limit y también un hard-limit (`--kill-after`).
