### ISSUE TITLE
DependencyHell: Duda sobre cómo preferir librerías mas nuevas

### ISSUE THREAD

**Issue by domingo2000** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#79]
Hola, me surge la duda de si para encontrar la librería más nueva tiene que ser si osi una regla, o podríamos simplemente pedirle a clingo que optimize ese valor?. Cual de ambas cosas sería mas eficiente? Pues logré fijar una regla pero no me da mucha seguridad asi que preferiria simplemente usar #optimize.

**Comment by Dietr1ch** [comment]
> Hola, me surge la duda de si para encontrar la librería más nueva tiene que ser si osi una regla, o podríamos simplemente pedirle a clingo que optimize ese valor?

Está abierto justamente para que puedan optar por ambas soluciones.

> Cual de ambas cosas sería mas eficiente?

Yo creo que depende de la implementación de las reglas. Sería algo interesante de experimentar.
