### ISSUE TITLE
[Tarea 1] Duda función get_number_coordinates

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#8]
En la tarea aparece lo siguiente:

![Screenshot from 2021-09-13 11-15-38](https://user-images.githubusercontent.com/47841749/133099910-d2bfc307-d366-4d5c-ae71-3d95b4612dda.png)

No entiendo muy bien esta funcion. Si lo podrian explicar seria ideal :)

**Comment by VicenteMerino** [comment]
Por lo que entiendo, es una lista donde los indices son los numeros de la celda, y retorna su posicion?

**Comment by vWing7** [comment]
Hola, efectivamente es lo que dices.

**Comment by Dietr1ch** [comment]
Si, es un mapeo inverso de número a su posición, en vez de el que tienen implícitamente con la matriz de numpy que es de posición a número.
