### ISSUE TITLE
[Tarea 2] Dependency Hell: intervalos cerrados de versiones

### ISSUE THREAD

**Issue by benjaminlillo** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#81]
Hola! Para esta parte, puede pasar que un programa que utilice una librería requiera un intervalo cerrado de versiones? Por ejemplo, que esto exista en la instancia:
```
requiresAtLeast(ls, libc, 0).
requiresAtMost(ls, libc, 2).  
```

**Comment by Dietr1ch** [comment]
Claro. Ambos predicados incluyen la versión mencionada. Eso es pedir que ![](https://render.githubusercontent.com/render/math?math=v_{libc}%20\in%20[0,%202]) y es legal.
