### ISSUE TITLE
[Tarea 2] Formato de las instancias en Statues

### ISSUE THREAD

**Issue by crvargasu** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#83]
Hola, en [`planning/statues/instances/0.lp`](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Planning-ASP/tree/master/planning/statues/instances/0.lp) de statues se define,

```
x(0..7).

start(at(0)).
goal(at(7)).

holds(2, red).
holds(3, red).
holds(5, red).
holds(7, red).
```

Me surge la duda de que se definió como `holds/2` en las posiciones donde no podemos avanzar, sin embargo, en el archivo [planning/strips.lp](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Planning-ASP/tree/master/planning/strips.lp) también se define `holds/2` a `holds(T, Fluent)`.
No entiendo si el holds de 0.lp afecta en algo al tener el mismo nombre? Porque tengo entendido que son funciones completamente distintas con el mismo nombre. Una es para indicar que no se puede avanzar y la otra es para indicar que se cumple un fluente en un tiempo T.

**Comment by Dietr1ch** [comment]
Hola, ambos archivos se refieren al mismo predicado `holds/2`.

Creo que te parece extraño, ya que esperabas derivar holds completamente en [`planning/statues/statues.lp`](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Planning-ASP/tree/master/planning/statues/statues.lp), pero este problema declara las instancias de manera en que deriva parte de `holds/2` "por ti".
La idea es que en este primer problema de planning de la tarea haya que hacer muy poquito.

Puedes pensar que una regla como `holds(T, red) :- time(T), willBeRedAt(T).` ya existe y que la instancia la dieron por medio de `willBeRedAt/1`.
