### ISSUE TITLE
Duda sobre holds en statues

### ISSUE THREAD

**Issue by domingo2000** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#86]
Hola, creo que al definir `holds(T, red)` este hace que se propage por lo de que si es que no hay una acción que cambie un fluente entonces el hold se mantiene. esto pues no he usado ninguna regla que derive una nueva luz roja y aún así me aparece como fluente del modelo lo siguiente
![image](https://user-images.githubusercontent.com/40220174/136618689-13647e6c-fa0a-4822-9b93-cac1ccd338dd.png)
está haciendo `holds(4, red)`, `holds(6, red)` automáticamente, es un error o tenemos que hacer alguna acción que haga que esto no ocurra??
PD: estoy usando la instancia del enunciado
![image](https://user-images.githubusercontent.com/40220174/136618805-c44fc3a4-526e-4ed0-953c-5ba15064b21b.png)

**Comment by crvargasu** [comment]
Hola. Me sumo a la duda
