### ISSUE TITLE
[Tarea 1] direnv: error .envrc is blocked. Run `direnv allow` to approve its content.

### ISSUE THREAD

**Issue by crvargasu** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#9]
Hola, al correr el programa principal tengo este error.

```direnv: error .envrc is blocked. Run `direnv allow` to approve its content.```

Al hacer `direnv allow` arroja el mismo error.

Busqué en google y me dice que debo desinstalar direnv con snap y luego instalarlo con apt, sin embargo, cuando desinstalo direnv con snap me arroja este error todo el tiempo

```bash: /snap/direnv/54/bin/direnv: No such file or directory```

Busqué más pero no encontre la solución a este problema.

Mi S.O: Ubuntu 20.04.2 LTS

**Comment by crvargasu** [comment]
Lo logré arreglar. La solucion fue efectivamente desinstalar direnv con snap y luego instalarlo con apt. Para que no arroje el erro que mencioné, luego de eso hay que reiniciar el computador.

**Comment by Dietr1ch** [comment]
Buena. Era un error particular de snap

Lo otro, direnv está configurado para usar nix al entrar al directorio y cargar el ambiente apropiado. Si no usas nix, puedes borrar el `.direnv`.

No sé si Debian/Ubuntu distribuyen nix, me imagino que si, pero no sé si el setup necesita algo especial o no. En general los packagers se preocupan de hacer los script de setup y todo funciona mágicamente, pero si tienes problemas con eso prefiero que borres el `.direnv` y uses Python con los paquetes de tu máquina no más.
