### ISSUE TITLE
[Tarea 2] posible error código base robots que sirven café

### ISSUE THREAD

**Issue by matumartinez** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#91]
`
fluent(has(Room, Drink)).
`

Esta línea creo que debería ser:

`
fluent(delivered(Room, Drink)).
`

O hay algo que estoy viendo mal?

**Comment by Dietr1ch** [comment]
> `fluent(has(Room, Drink)).`
> 
> Esta línea creo que debería ser:
> 
> `fluent(delivered(Room, Drink)).`
> 
> O hay algo que estoy viendo mal?

(Contexto: [main.org:#café-a-la-oficina](https://github.com/IIC2613-Inteligencia-Artificial-2021-2/Assignment-2/blob/master/main.org#café-a-la-oficina))

Claro, debería ser `has` en vez de `delivered`.
