### ISSUE TITLE
Duda estado inicial en robot que reparte café Tarea 2

### ISSUE THREAD

**Issue by fbarrosalcalde** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#92]
Hola, en la pregunta de un robot que reparte café, el estado de las puertas al comienzo (isOpen(Door) y isClosed(Door)) debe ir en el start() de la instancia? O se asume que todas comienzan cerradas?

**Comment by Dietr1ch** [comment]
Si no se entregan en el input se asume que parten cerradas.

Pueden "rechazar" inputs en que `isOpen(d0)` y `isClosed(d0)` sean verdaderos en start agregando restricciones.
