### ISSUE TITLE
[Tarea 2] Instancias de los problemas - Proposiciones nuevas

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#96]
Hola, en las instancias de los problemas se pueden agregar proposiciones?

Que en particular, en el de block siento que falta una que diga algo como `ìsTable(table)`.

![image](https://user-images.githubusercontent.com/47841749/136859732-5d3f4b22-407f-4c2f-aa3f-5f288a9b73d6.png)

**Comment by Dietr1ch** [comment]
No, pero esa sería una proposición común para todos las instancias y debería ser parte de tu modelo.
