### ISSUE TITLE
[Tarea 2] Duda sobre oficinas en problema Coffee

### ISSUE THREAD

**Issue by domingo2000** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#97]
Hola, me surge la duda si es necesario modelar el problema de los cafés incluyendo la sentencia `office(Office)`, pues no veo la diferencia en tratar una oficina como simplemente una sala (Room) más, ya que se puede entregar café tanto a una oficina como a una sala.

**Comment by Dietr1ch** [comment]
Sólo se puede preparar café en la Cocina, y por eso existe `kitchen/1`. El predicado `office/1` existe sólo como contraparte de `kitchen`, pero es necesario al notar que el input puede decir algo como `office(o1)` sin además decir que `room(o1)`.

Una vez que pasas por ese detalle, claro, `office/1` se vuelve innecesario, ya que como dices `room/1` es suficiente y más general para manejar los pedidos.
