### ISSUE TITLE
Transformar acción de 3 inputs a una de dos en clingo

### ISSUE THREAD

**Issue by fbarrosalcalde** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#98]
Hola, tengo una acción que tiene 3 inputs y la quiero transformar a una que tenga dos para cumplir con el output que se pide en el enunciado. En el fondo, quiero pasar de esto: exec(T, actionOne(a, b, c)) a esto: exec(T, action(a, c)), pero sin modificar el código de la acción, se puede?

**Comment by Dietr1ch** [comment]
No es necesario, puedes tener argumentos adicionales. Vamos a intentar considerar el output de manera que les de libertad al diseñar sus modelos.


Ahora, ¿cómo se haría esto? Creo que lo más fácil sería tener un predicado derivado de `exec` que oculte los argumentos innecesarios al momento de dar una solución, algo así,

```
simple_exec(T, simpleAction(A, B)) :- exec(T, rawAction(A, B, C)).
```

¿Por qué otro predicado "exec" y otra "acción"? Supongo que ya te diste cuenta que no era simple cambiar `exec` o la acción directamente, ya que algunas de las reglas base de la "librería" de STRIPS que tenemos te iban a molestar. Por ejemplo la restricción de que es solo un `exec` por instante de tiempo no te deja usar `exec(T, simpleAction(A)) :- exec(A, rawAction(A, B)).`, ya que eso haría insatisfacible los modelos que usen esa acción.
