### ISSUE TITLE
[Tarea 2] Statues - Duda parámetro k

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2613-Inteligencia-Artificial-2021-2/Syllabus#99]
Hola, en la instancia de statues, sale que el k debería ser 10, sin embargo necesito hacer 7 movimientos para llegar a la solución (0-1, 1-2, 2-3, 3-4, 4-5, 5-6 y 6-7) y tengo 4 tiempos muertos, como time va desde 0 hasta k-1, tengo 10 instantes de tiempos, lo que me deja con 10-4=6 movimientos posibles, con lo que llegaría a un modelo insatisfacible, por lo que quería saber si está bien que cambiemos este parámetro a k=11.

**Comment by Dietr1ch** [comment]
Si, debería ser `11`.
